// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package http

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ChallengeCategory.
const (
	ChallengeCategoryAwd       ChallengeCategory = "awd"
	ChallengeCategoryCrypto    ChallengeCategory = "crypto"
	ChallengeCategoryForensics ChallengeCategory = "forensics"
	ChallengeCategoryMisc      ChallengeCategory = "misc"
	ChallengeCategoryPwn       ChallengeCategory = "pwn"
	ChallengeCategoryReverse   ChallengeCategory = "reverse"
	ChallengeCategoryWeb       ChallengeCategory = "web"
)

// Valid indicates whether the value is a known member of the ChallengeCategory enum.
func (e ChallengeCategory) Valid() bool {
	switch e {
	case ChallengeCategoryAwd:
		return true
	case ChallengeCategoryCrypto:
		return true
	case ChallengeCategoryForensics:
		return true
	case ChallengeCategoryMisc:
		return true
	case ChallengeCategoryPwn:
		return true
	case ChallengeCategoryReverse:
		return true
	case ChallengeCategoryWeb:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeDifficulty.
const (
	ChallengeDifficultyEasy   ChallengeDifficulty = "easy"
	ChallengeDifficultyHard   ChallengeDifficulty = "hard"
	ChallengeDifficultyMedium ChallengeDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the ChallengeDifficulty enum.
func (e ChallengeDifficulty) Valid() bool {
	switch e {
	case ChallengeDifficultyEasy:
		return true
	case ChallengeDifficultyHard:
		return true
	case ChallengeDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeType.
const (
	ChallengeTypeDynamic ChallengeType = "dynamic"
	ChallengeTypeStatic  ChallengeType = "static"
)

// Valid indicates whether the value is a known member of the ChallengeType enum.
func (e ChallengeType) Valid() bool {
	switch e {
	case ChallengeTypeDynamic:
		return true
	case ChallengeTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestCategory.
const (
	CreateChallengeRequestCategoryAwd       CreateChallengeRequestCategory = "awd"
	CreateChallengeRequestCategoryCrypto    CreateChallengeRequestCategory = "crypto"
	CreateChallengeRequestCategoryForensics CreateChallengeRequestCategory = "forensics"
	CreateChallengeRequestCategoryMisc      CreateChallengeRequestCategory = "misc"
	CreateChallengeRequestCategoryPwn       CreateChallengeRequestCategory = "pwn"
	CreateChallengeRequestCategoryReverse   CreateChallengeRequestCategory = "reverse"
	CreateChallengeRequestCategoryWeb       CreateChallengeRequestCategory = "web"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestCategory enum.
func (e CreateChallengeRequestCategory) Valid() bool {
	switch e {
	case CreateChallengeRequestCategoryAwd:
		return true
	case CreateChallengeRequestCategoryCrypto:
		return true
	case CreateChallengeRequestCategoryForensics:
		return true
	case CreateChallengeRequestCategoryMisc:
		return true
	case CreateChallengeRequestCategoryPwn:
		return true
	case CreateChallengeRequestCategoryReverse:
		return true
	case CreateChallengeRequestCategoryWeb:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestDifficulty.
const (
	CreateChallengeRequestDifficultyEasy   CreateChallengeRequestDifficulty = "easy"
	CreateChallengeRequestDifficultyHard   CreateChallengeRequestDifficulty = "hard"
	CreateChallengeRequestDifficultyMedium CreateChallengeRequestDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestDifficulty enum.
func (e CreateChallengeRequestDifficulty) Valid() bool {
	switch e {
	case CreateChallengeRequestDifficultyEasy:
		return true
	case CreateChallengeRequestDifficultyHard:
		return true
	case CreateChallengeRequestDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestType.
const (
	CreateChallengeRequestTypeDynamic CreateChallengeRequestType = "dynamic"
	CreateChallengeRequestTypeStatic  CreateChallengeRequestType = "static"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestType enum.
func (e CreateChallengeRequestType) Valid() bool {
	switch e {
	case CreateChallengeRequestTypeDynamic:
		return true
	case CreateChallengeRequestTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for GameStatus.
const (
	GameStatusActive GameStatus = "active"
	GameStatusDraft  GameStatus = "draft"
	GameStatusEnded  GameStatus = "ended"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case GameStatusActive:
		return true
	case GameStatusDraft:
		return true
	case GameStatusEnded:
		return true
	default:
		return false
	}
}

// Defines values for GameRegistrationMode.
const (
	GameRegistrationModeAutoAccept GameRegistrationMode = "auto_accept"
	GameRegistrationModeReview     GameRegistrationMode = "review"
)

// Valid indicates whether the value is a known member of the GameRegistrationMode enum.
func (e GameRegistrationMode) Valid() bool {
	switch e {
	case GameRegistrationModeAutoAccept:
		return true
	case GameRegistrationModeReview:
		return true
	default:
		return false
	}
}

// Defines values for GameChallengeDetailCategory.
const (
	Awd       GameChallengeDetailCategory = "awd"
	Crypto    GameChallengeDetailCategory = "crypto"
	Forensics GameChallengeDetailCategory = "forensics"
	Misc      GameChallengeDetailCategory = "misc"
	Pwn       GameChallengeDetailCategory = "pwn"
	Reverse   GameChallengeDetailCategory = "reverse"
	Web       GameChallengeDetailCategory = "web"
)

// Valid indicates whether the value is a known member of the GameChallengeDetailCategory enum.
func (e GameChallengeDetailCategory) Valid() bool {
	switch e {
	case Awd:
		return true
	case Crypto:
		return true
	case Forensics:
		return true
	case Misc:
		return true
	case Pwn:
		return true
	case Reverse:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for GameChallengeDetailType.
const (
	Dynamic GameChallengeDetailType = "dynamic"
	Static  GameChallengeDetailType = "static"
)

// Valid indicates whether the value is a known member of the GameChallengeDetailType enum.
func (e GameChallengeDetailType) Valid() bool {
	switch e {
	case Dynamic:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for SubmitResultBloodType.
const (
	First  SubmitResultBloodType = "first"
	Second SubmitResultBloodType = "second"
	Third  SubmitResultBloodType = "third"
)

// Valid indicates whether the value is a known member of the SubmitResultBloodType enum.
func (e SubmitResultBloodType) Valid() bool {
	switch e {
	case First:
		return true
	case Second:
		return true
	case Third:
		return true
	default:
		return false
	}
}

// Defines values for UpdateGameRequestStatus.
const (
	UpdateGameRequestStatusActive UpdateGameRequestStatus = "active"
	UpdateGameRequestStatusDraft  UpdateGameRequestStatus = "draft"
	UpdateGameRequestStatusEnded  UpdateGameRequestStatus = "ended"
)

// Valid indicates whether the value is a known member of the UpdateGameRequestStatus enum.
func (e UpdateGameRequestStatus) Valid() bool {
	switch e {
	case UpdateGameRequestStatusActive:
		return true
	case UpdateGameRequestStatusDraft:
		return true
	case UpdateGameRequestStatusEnded:
		return true
	default:
		return false
	}
}

// Defines values for UpdateGameRequestRegistrationMode.
const (
	UpdateGameRequestRegistrationModeAutoAccept UpdateGameRequestRegistrationMode = "auto_accept"
	UpdateGameRequestRegistrationModeReview     UpdateGameRequestRegistrationMode = "review"
)

// Valid indicates whether the value is a known member of the UpdateGameRequestRegistrationMode enum.
func (e UpdateGameRequestRegistrationMode) Valid() bool {
	switch e {
	case UpdateGameRequestRegistrationModeAutoAccept:
		return true
	case UpdateGameRequestRegistrationModeReview:
		return true
	default:
		return false
	}
}

// Defines values for UserInfoRole.
const (
	Admin       UserInfoRole = "admin"
	Judge       UserInfoRole = "judge"
	SuperAdmin  UserInfoRole = "super_admin"
	TeamCaptain UserInfoRole = "team_captain"
	User        UserInfoRole = "user"
)

// Valid indicates whether the value is a known member of the UserInfoRole enum.
func (e UserInfoRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Judge:
		return true
	case SuperAdmin:
		return true
	case TeamCaptain:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for UserInfoStatus.
const (
	Active UserInfoStatus = "active"
	Banned UserInfoStatus = "banned"
)

// Valid indicates whether the value is a known member of the UserInfoStatus enum.
func (e UserInfoStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Banned:
		return true
	default:
		return false
	}
}

// AddChallengeToGameRequest defines model for AddChallengeToGameRequest.
type AddChallengeToGameRequest struct {
	ChallengeId   int  `json:"challenge_id"`
	ScoreOverride *int `json:"score_override,omitempty"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	Attachments *string              `json:"attachments,omitempty"`
	BaseScore   *int                 `json:"base_score,omitempty"`
	Category    ChallengeCategory    `json:"category"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	DecayRate   *float32             `json:"decay_rate,omitempty"`
	Description *string              `json:"description,omitempty"`
	Difficulty  *ChallengeDifficulty `json:"difficulty,omitempty"`
	Hints       *string              `json:"hints,omitempty"`
	Id          int                  `json:"id"`
	IsVisible   *bool                `json:"is_visible,omitempty"`
	MinScore    *int                 `json:"min_score,omitempty"`
	Title       string               `json:"title"`
	Type        ChallengeType        `json:"type"`
}

// ChallengeCategory defines model for Challenge.Category.
type ChallengeCategory string

// ChallengeDifficulty defines model for Challenge.Difficulty.
type ChallengeDifficulty string

// ChallengeType defines model for Challenge.Type.
type ChallengeType string

// CreateChallengeRequest defines model for CreateChallengeRequest.
type CreateChallengeRequest struct {
	Attachments   *string                           `json:"attachments,omitempty"`
	BaseScore     *int                              `json:"base_score,omitempty"`
	Category      CreateChallengeRequestCategory    `json:"category"`
	ContainerSpec *string                           `json:"container_spec,omitempty"`
	DecayRate     *float32                          `json:"decay_rate,omitempty"`
	Description   *string                           `json:"description,omitempty"`
	Difficulty    *CreateChallengeRequestDifficulty `json:"difficulty,omitempty"`
	Flag          string                            `json:"flag"`
	FlagFormat    *string                           `json:"flag_format,omitempty"`
	Hints         *string                           `json:"hints,omitempty"`
	IsVisible     *bool                             `json:"is_visible,omitempty"`
	MaxAttempts   *int                              `json:"max_attempts,omitempty"`
	MinScore      *int                              `json:"min_score,omitempty"`
	Title         string                            `json:"title"`
	Type          *CreateChallengeRequestType       `json:"type,omitempty"`
}

// CreateChallengeRequestCategory defines model for CreateChallengeRequest.Category.
type CreateChallengeRequestCategory string

// CreateChallengeRequestDifficulty defines model for CreateChallengeRequest.Difficulty.
type CreateChallengeRequestDifficulty string

// CreateChallengeRequestType defines model for CreateChallengeRequest.Type.
type CreateChallengeRequestType string

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	Description      *string               `json:"description,omitempty"`
	EndTime          time.Time             `json:"end_time"`
	IsPublic         *bool                 `json:"is_public,omitempty"`
	MaxTeamMembers   *int                  `json:"max_team_members,omitempty"`
	Name             string                `json:"name"`
	Notice           *string               `json:"notice,omitempty"`
	RegistrationMode *GameRegistrationMode `json:"registration_mode,omitempty"`
	StartTime        time.Time             `json:"start_time"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Game defines model for Game.
type Game struct {
	CreatedAt        *time.Time            `json:"created_at,omitempty"`
	CreatedBy        *int                  `json:"created_by,omitempty"`
	Description      *string               `json:"description,omitempty"`
	EndTime          time.Time             `json:"end_time"`
	Id               int                   `json:"id"`
	IsPublic         *bool                 `json:"is_public,omitempty"`
	MaxTeamMembers   *int                  `json:"max_team_members,omitempty"`
	Name             string                `json:"name"`
	Notice           *string               `json:"notice,omitempty"`
	RegistrationMode *GameRegistrationMode `json:"registration_mode,omitempty"`
	StartTime        time.Time             `json:"start_time"`
	Status           GameStatus            `json:"status"`
}

// GameStatus defines model for Game.Status.
type GameStatus string

// GameRegistrationMode defines model for Game.RegistrationMode.
type GameRegistrationMode string

// GameChallengeDetail defines model for GameChallengeDetail.
type GameChallengeDetail struct {
	BloodTeam  *string                     `json:"blood_team,omitempty"`
	Category   GameChallengeDetailCategory `json:"category"`
	Difficulty *string                     `json:"difficulty,omitempty"`
	Id         int                         `json:"id"`
	Score      int                         `json:"score"`
	SolveCount *int                        `json:"solve_count,omitempty"`
	Solved     *bool                       `json:"solved,omitempty"`
	Title      string                      `json:"title"`
	Type       GameChallengeDetailType     `json:"type"`
}

// GameChallengeDetailCategory defines model for GameChallengeDetail.Category.
type GameChallengeDetailCategory string

// GameChallengeDetailType defines model for GameChallengeDetail.Type.
type GameChallengeDetailType string

// GameSubmitFlagRequest defines model for GameSubmitFlagRequest.
type GameSubmitFlagRequest struct {
	Flag   string `json:"flag"`
	TeamId int    `json:"team_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// JoinGameRequest defines model for JoinGameRequest.
type JoinGameRequest struct {
	TeamId int `json:"team_id"`
}

// JoinTeamRequest defines model for JoinTeamRequest.
type JoinTeamRequest struct {
	InviteCode string `json:"invite_code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Username Username or email
	Username string `json:"username"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// Scoreboard defines model for Scoreboard.
type Scoreboard struct {
	Entries []ScoreboardEntry `json:"entries"`
	GameId  int               `json:"game_id"`
}

// GameParticipation defines model for GameParticipation.
type GameParticipation struct {
	HasTeam      bool                  `json:"has_team"`
	Participated bool                  `json:"participated"`
	Status       *GameParticipationStatus `json:"status,omitempty"`
	Team         *GameParticipationTeam `json:"team,omitempty"`
}

// GameParticipationStatus defines model for GameParticipation.Status.
type GameParticipationStatus string

const (
	GameParticipationStatusAccepted GameParticipationStatus = "accepted"
	GameParticipationStatusPending  GameParticipationStatus = "pending"
	GameParticipationStatusRejected GameParticipationStatus = "rejected"
)

// GameParticipationTeam defines model for GameParticipation.Team.
type GameParticipationTeam struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// ScoreboardEntry defines model for ScoreboardEntry.
type ScoreboardEntry struct {
	LastSolve  *time.Time `json:"last_solve,omitempty"`
	Rank       int        `json:"rank"`
	Score      int        `json:"score"`
	SolveCount int        `json:"solve_count"`
	TeamId     int        `json:"team_id"`
	TeamName   string     `json:"team_name"`
}

// SubmitFlagRequest defines model for SubmitFlagRequest.
type SubmitFlagRequest struct {
	Flag   string `json:"flag"`
	GameId int    `json:"game_id"`
}

// SubmitResult defines model for SubmitResult.
type SubmitResult struct {
	BloodType *SubmitResultBloodType `json:"blood_type,omitempty"`
	Correct   bool                   `json:"correct"`
	Message   string                 `json:"message"`
	Score     *int                   `json:"score,omitempty"`
}

// SubmitResultBloodType defines model for SubmitResult.BloodType.
type SubmitResultBloodType string

// Team defines model for Team.
type Team struct {
	CreatedAt  *time.Time    `json:"created_at,omitempty"`
	Id         int           `json:"id"`
	InviteCode string        `json:"invite_code"`
	Members    *[]TeamMember `json:"members,omitempty"`
	Name       string        `json:"name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	Id     int    `json:"id"`
	Role   string `json:"role"`
	TeamId int    `json:"team_id"`
	UserId int    `json:"user_id"`
}

// UpdateChallengeRequest defines model for UpdateChallengeRequest.
type UpdateChallengeRequest struct {
	BaseScore   *int     `json:"base_score,omitempty"`
	Category    *string  `json:"category,omitempty"`
	DecayRate   *float32 `json:"decay_rate,omitempty"`
	Description *string  `json:"description,omitempty"`
	Difficulty  *string  `json:"difficulty,omitempty"`
	Flag        *string  `json:"flag,omitempty"`
	IsVisible   *bool    `json:"is_visible,omitempty"`
	MinScore    *int     `json:"min_score,omitempty"`
	Title       *string  `json:"title,omitempty"`
	Type        *string  `json:"type,omitempty"`
}

// UpdateGameRequest defines model for UpdateGameRequest.
type UpdateGameRequest struct {
	Description      *string                            `json:"description,omitempty"`
	EndTime          *time.Time                         `json:"end_time,omitempty"`
	IsPublic         *bool                              `json:"is_public,omitempty"`
	MaxTeamMembers   *int                               `json:"max_team_members,omitempty"`
	Name             *string                            `json:"name,omitempty"`
	Notice           *string                            `json:"notice,omitempty"`
	RegistrationMode *UpdateGameRequestRegistrationMode `json:"registration_mode,omitempty"`
	StartTime        *time.Time                         `json:"start_time,omitempty"`
	Status           *UpdateGameRequestStatus           `json:"status,omitempty"`
}

// UpdateGameRequestStatus defines model for UpdateGameRequest.Status.
type UpdateGameRequestStatus string

// UpdateGameRequestRegistrationMode defines model for UpdateGameRequest.RegistrationMode.
type UpdateGameRequestRegistrationMode string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	CreatedAt *time.Time     `json:"created_at,omitempty"`
	Email     string         `json:"email"`
	Id        int            `json:"id"`
	Role      UserInfoRole   `json:"role"`
	Status    UserInfoStatus `json:"status"`
	Username  string         `json:"username"`
}

// UserInfoRole defines model for UserInfo.Role.
type UserInfoRole string

// UserInfoStatus defines model for UserInfo.Status.
type UserInfoStatus string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListChallengesParams defines parameters for ListChallenges.
type ListChallengesParams struct {
	Category   *string `form:"category,omitempty" json:"category,omitempty"`
	ShowHidden *bool   `form:"show_hidden,omitempty" json:"show_hidden,omitempty"`
}

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	All *bool `form:"all,omitempty" json:"all,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateChallengeJSONRequestBody defines body for CreateChallenge for application/json ContentType.
type CreateChallengeJSONRequestBody = CreateChallengeRequest

// UpdateChallengeJSONRequestBody defines body for UpdateChallenge for application/json ContentType.
type UpdateChallengeJSONRequestBody = UpdateChallengeRequest

// SubmitChallengeFlagJSONRequestBody defines body for SubmitChallengeFlag for application/json ContentType.
type SubmitChallengeFlagJSONRequestBody = SubmitFlagRequest

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// UpdateGameJSONRequestBody defines body for UpdateGame for application/json ContentType.
type UpdateGameJSONRequestBody = UpdateGameRequest

// AddChallengeToGameJSONRequestBody defines body for AddChallengeToGame for application/json ContentType.
type AddChallengeToGameJSONRequestBody = AddChallengeToGameRequest

// SubmitGameFlagJSONRequestBody defines body for SubmitGameFlag for application/json ContentType.
type SubmitGameFlagJSONRequestBody = GameSubmitFlagRequest

// JoinGameJSONRequestBody defines body for JoinGame for application/json ContentType.
type JoinGameJSONRequestBody = JoinGameRequest

// LeaveGameJSONRequestBody defines body for LeaveGame for application/json ContentType.
type LeaveGameJSONRequestBody = JoinGameRequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// JoinTeamJSONRequestBody defines body for JoinTeam for application/json ContentType.
type JoinTeamJSONRequestBody = JoinTeamRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username or email
	// (POST /api/auth/login)
	Login(c *gin.Context)
	// Invalidate session
	// (POST /api/auth/logout)
	Logout(c *gin.Context)
	// Get current user info
	// (GET /api/auth/me)
	GetMe(c *gin.Context)
	// Register a new user
	// (POST /api/auth/register)
	Register(c *gin.Context)
	// List challenges
	// (GET /api/challenges)
	ListChallenges(c *gin.Context, params ListChallengesParams)
	// Create a challenge (admin)
	// (POST /api/challenges)
	CreateChallenge(c *gin.Context)
	// Delete a challenge (admin)
	// (DELETE /api/challenges/{id})
	DeleteChallenge(c *gin.Context, id int)
	// Get a challenge
	// (GET /api/challenges/{id})
	GetChallenge(c *gin.Context, id int)
	// Update a challenge (admin)
	// (PUT /api/challenges/{id})
	UpdateChallenge(c *gin.Context, id int)
	// Submit flag for standalone challenge
	// (POST /api/challenges/{id}/submit)
	SubmitChallengeFlag(c *gin.Context, id int)
	// List games
	// (GET /api/games)
	ListGames(c *gin.Context, params ListGamesParams)
	// Create a game (admin)
	// (POST /api/games)
	CreateGame(c *gin.Context)
	// Get a game
	// (GET /api/games/{id})
	GetGame(c *gin.Context, id int)
	// Update a game (admin)
	// (PUT /api/games/{id})
	UpdateGame(c *gin.Context, id int)
	// Get challenges in a game
	// (GET /api/games/{id}/challenges)
	GetGameChallenges(c *gin.Context, id int)
	// Add a challenge to a game (admin)
	// (POST /api/games/{id}/challenges)
	AddChallengeToGame(c *gin.Context, id int)
	// Remove a challenge from a game (admin)
	// (DELETE /api/games/{id}/challenges/{challengeId})
	RemoveChallengeFromGame(c *gin.Context, id int, challengeId int)
	// Submit flag for a challenge in a game
	// (POST /api/games/{id}/challenges/{challengeId}/submit)
	SubmitGameFlag(c *gin.Context, id int, challengeId int)
	// Join a game with a team
	// (POST /api/games/{id}/join)
	JoinGame(c *gin.Context, id int)
	// Leave a game
	// (DELETE /api/games/{id}/leave)
	LeaveGame(c *gin.Context, id int)
	// Get game scoreboard
	// (GET /api/games/{id}/scoreboard)
	GetScoreboard(c *gin.Context, id int)
	// Get my participation status in a game
	// (GET /api/games/{id}/participation)
	GetGameParticipation(c *gin.Context, id int)
	// Health check
	// (GET /api/healthz)
	Healthz(c *gin.Context)
	// Create a team
	// (POST /api/teams)
	CreateTeam(c *gin.Context)
	// Join a team by invite code
	// (POST /api/teams/join)
	JoinTeam(c *gin.Context)
	// Leave current team
	// (POST /api/teams/leave)
	LeaveTeam(c *gin.Context)
	// Get my team
	// (GET /api/teams/my)
	GetMyTeam(c *gin.Context)
	// Remove a team member (captain only)
	// (DELETE /api/teams/{teamId}/members/{memberId})
	RemoveTeamMember(c *gin.Context, teamId int, memberId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ListChallenges operation middleware
func (siw *ServerInterfaceWrapper) ListChallenges(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChallengesParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "show_hidden" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "show_hidden", c.Request.URL.Query(), &params.ShowHidden, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter show_hidden: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChallenges(c, params)
}

// CreateChallenge operation middleware
func (siw *ServerInterfaceWrapper) CreateChallenge(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChallenge(c)
}

// DeleteChallenge operation middleware
func (siw *ServerInterfaceWrapper) DeleteChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChallenge(c, id)
}

// GetChallenge operation middleware
func (siw *ServerInterfaceWrapper) GetChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallenge(c, id)
}

// UpdateChallenge operation middleware
func (siw *ServerInterfaceWrapper) UpdateChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateChallenge(c, id)
}

// SubmitChallengeFlag operation middleware
func (siw *ServerInterfaceWrapper) SubmitChallengeFlag(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitChallengeFlag(c, id)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "all" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "all", c.Request.URL.Query(), &params.All, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter all: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGames(c, params)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGame(c)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGame(c, id)
}

// UpdateGame operation middleware
func (siw *ServerInterfaceWrapper) UpdateGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGame(c, id)
}

// GetGameChallenges operation middleware
func (siw *ServerInterfaceWrapper) GetGameChallenges(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameChallenges(c, id)
}

// AddChallengeToGame operation middleware
func (siw *ServerInterfaceWrapper) AddChallengeToGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddChallengeToGame(c, id)
}

// RemoveChallengeFromGame operation middleware
func (siw *ServerInterfaceWrapper) RemoveChallengeFromGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveChallengeFromGame(c, id, challengeId)
}

// SubmitGameFlag operation middleware
func (siw *ServerInterfaceWrapper) SubmitGameFlag(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitGameFlag(c, id, challengeId)
}

// JoinGame operation middleware
func (siw *ServerInterfaceWrapper) JoinGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinGame(c, id)
}

// GetGameParticipation operation middleware
func (siw *ServerInterfaceWrapper) GetGameParticipation(c *gin.Context) {

	var err error
	_ = err

	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameParticipation(c, id)
}

// LeaveGame operation middleware
func (siw *ServerInterfaceWrapper) LeaveGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveGame(c, id)
}

// GetScoreboard operation middleware
func (siw *ServerInterfaceWrapper) GetScoreboard(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetScoreboard(c, id)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTeam(c)
}

// JoinTeam operation middleware
func (siw *ServerInterfaceWrapper) JoinTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinTeam(c)
}

// LeaveTeam operation middleware
func (siw *ServerInterfaceWrapper) LeaveTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveTeam(c)
}

// GetMyTeam operation middleware
func (siw *ServerInterfaceWrapper) GetMyTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyTeam(c)
}

// RemoveTeamMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTeamMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamId" -------------
	var teamId int

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveTeamMember(c, teamId, memberId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/api/challenges", wrapper.ListChallenges)
	router.POST(options.BaseURL+"/api/challenges", wrapper.CreateChallenge)
	router.DELETE(options.BaseURL+"/api/challenges/:id", wrapper.DeleteChallenge)
	router.GET(options.BaseURL+"/api/challenges/:id", wrapper.GetChallenge)
	router.PUT(options.BaseURL+"/api/challenges/:id", wrapper.UpdateChallenge)
	router.POST(options.BaseURL+"/api/challenges/:id/submit", wrapper.SubmitChallengeFlag)
	router.GET(options.BaseURL+"/api/games", wrapper.ListGames)
	router.POST(options.BaseURL+"/api/games", wrapper.CreateGame)
	router.GET(options.BaseURL+"/api/games/:id", wrapper.GetGame)
	router.PUT(options.BaseURL+"/api/games/:id", wrapper.UpdateGame)
	router.GET(options.BaseURL+"/api/games/:id/challenges", wrapper.GetGameChallenges)
	router.POST(options.BaseURL+"/api/games/:id/challenges", wrapper.AddChallengeToGame)
	router.DELETE(options.BaseURL+"/api/games/:id/challenges/:challengeId", wrapper.RemoveChallengeFromGame)
	router.POST(options.BaseURL+"/api/games/:id/challenges/:challengeId/submit", wrapper.SubmitGameFlag)
	router.POST(options.BaseURL+"/api/games/:id/join", wrapper.JoinGame)
	router.GET(options.BaseURL+"/api/games/:id/participation", wrapper.GetGameParticipation)
	router.DELETE(options.BaseURL+"/api/games/:id/leave", wrapper.LeaveGame)
	router.GET(options.BaseURL+"/api/games/:id/scoreboard", wrapper.GetScoreboard)
	router.GET(options.BaseURL+"/api/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/api/teams", wrapper.CreateTeam)
	router.POST(options.BaseURL+"/api/teams/join", wrapper.JoinTeam)
	router.POST(options.BaseURL+"/api/teams/leave", wrapper.LeaveTeam)
	router.GET(options.BaseURL+"/api/teams/my", wrapper.GetMyTeam)
	router.DELETE(options.BaseURL+"/api/teams/:teamId/members/:memberId", wrapper.RemoveTeamMember)
}
