// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package http

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ChallengeCategory.
const (
	ChallengeCategoryAwd       ChallengeCategory = "awd"
	ChallengeCategoryCrypto    ChallengeCategory = "crypto"
	ChallengeCategoryForensics ChallengeCategory = "forensics"
	ChallengeCategoryMisc      ChallengeCategory = "misc"
	ChallengeCategoryPwn       ChallengeCategory = "pwn"
	ChallengeCategoryReverse   ChallengeCategory = "reverse"
	ChallengeCategoryWeb       ChallengeCategory = "web"
)

// Valid indicates whether the value is a known member of the ChallengeCategory enum.
func (e ChallengeCategory) Valid() bool {
	switch e {
	case ChallengeCategoryAwd:
		return true
	case ChallengeCategoryCrypto:
		return true
	case ChallengeCategoryForensics:
		return true
	case ChallengeCategoryMisc:
		return true
	case ChallengeCategoryPwn:
		return true
	case ChallengeCategoryReverse:
		return true
	case ChallengeCategoryWeb:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeDifficulty.
const (
	ChallengeDifficultyEasy   ChallengeDifficulty = "easy"
	ChallengeDifficultyHard   ChallengeDifficulty = "hard"
	ChallengeDifficultyMedium ChallengeDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the ChallengeDifficulty enum.
func (e ChallengeDifficulty) Valid() bool {
	switch e {
	case ChallengeDifficultyEasy:
		return true
	case ChallengeDifficultyHard:
		return true
	case ChallengeDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeType.
const (
	ChallengeTypeDynamic ChallengeType = "dynamic"
	ChallengeTypeStatic  ChallengeType = "static"
)

// Valid indicates whether the value is a known member of the ChallengeType enum.
func (e ChallengeType) Valid() bool {
	switch e {
	case ChallengeTypeDynamic:
		return true
	case ChallengeTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeInstanceStatus.
const (
	Idle    ChallengeInstanceStatus = "idle"
	Running ChallengeInstanceStatus = "running"
)

// Valid indicates whether the value is a known member of the ChallengeInstanceStatus enum.
func (e ChallengeInstanceStatus) Valid() bool {
	switch e {
	case Idle:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestCategory.
const (
	CreateChallengeRequestCategoryAwd       CreateChallengeRequestCategory = "awd"
	CreateChallengeRequestCategoryCrypto    CreateChallengeRequestCategory = "crypto"
	CreateChallengeRequestCategoryForensics CreateChallengeRequestCategory = "forensics"
	CreateChallengeRequestCategoryMisc      CreateChallengeRequestCategory = "misc"
	CreateChallengeRequestCategoryPwn       CreateChallengeRequestCategory = "pwn"
	CreateChallengeRequestCategoryReverse   CreateChallengeRequestCategory = "reverse"
	CreateChallengeRequestCategoryWeb       CreateChallengeRequestCategory = "web"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestCategory enum.
func (e CreateChallengeRequestCategory) Valid() bool {
	switch e {
	case CreateChallengeRequestCategoryAwd:
		return true
	case CreateChallengeRequestCategoryCrypto:
		return true
	case CreateChallengeRequestCategoryForensics:
		return true
	case CreateChallengeRequestCategoryMisc:
		return true
	case CreateChallengeRequestCategoryPwn:
		return true
	case CreateChallengeRequestCategoryReverse:
		return true
	case CreateChallengeRequestCategoryWeb:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestDifficulty.
const (
	CreateChallengeRequestDifficultyEasy   CreateChallengeRequestDifficulty = "easy"
	CreateChallengeRequestDifficultyHard   CreateChallengeRequestDifficulty = "hard"
	CreateChallengeRequestDifficultyMedium CreateChallengeRequestDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestDifficulty enum.
func (e CreateChallengeRequestDifficulty) Valid() bool {
	switch e {
	case CreateChallengeRequestDifficultyEasy:
		return true
	case CreateChallengeRequestDifficultyHard:
		return true
	case CreateChallengeRequestDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for CreateChallengeRequestType.
const (
	CreateChallengeRequestTypeDynamic CreateChallengeRequestType = "dynamic"
	CreateChallengeRequestTypeStatic  CreateChallengeRequestType = "static"
)

// Valid indicates whether the value is a known member of the CreateChallengeRequestType enum.
func (e CreateChallengeRequestType) Valid() bool {
	switch e {
	case CreateChallengeRequestTypeDynamic:
		return true
	case CreateChallengeRequestTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for CreateGameRequestRegistrationMode.
const (
	CreateGameRequestRegistrationModeAutoAccept CreateGameRequestRegistrationMode = "auto_accept"
	CreateGameRequestRegistrationModeReview     CreateGameRequestRegistrationMode = "review"
)

// Valid indicates whether the value is a known member of the CreateGameRequestRegistrationMode enum.
func (e CreateGameRequestRegistrationMode) Valid() bool {
	switch e {
	case CreateGameRequestRegistrationModeAutoAccept:
		return true
	case CreateGameRequestRegistrationModeReview:
		return true
	default:
		return false
	}
}

// Defines values for GameRegistrationMode.
const (
	GameRegistrationModeAutoAccept GameRegistrationMode = "auto_accept"
	GameRegistrationModeReview     GameRegistrationMode = "review"
)

// Valid indicates whether the value is a known member of the GameRegistrationMode enum.
func (e GameRegistrationMode) Valid() bool {
	switch e {
	case GameRegistrationModeAutoAccept:
		return true
	case GameRegistrationModeReview:
		return true
	default:
		return false
	}
}

// Defines values for GameStatus.
const (
	GameStatusActive GameStatus = "active"
	GameStatusDraft  GameStatus = "draft"
	GameStatusEnded  GameStatus = "ended"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case GameStatusActive:
		return true
	case GameStatusDraft:
		return true
	case GameStatusEnded:
		return true
	default:
		return false
	}
}

// Defines values for GameChallengeDetailCategory.
const (
	Awd       GameChallengeDetailCategory = "awd"
	Crypto    GameChallengeDetailCategory = "crypto"
	Forensics GameChallengeDetailCategory = "forensics"
	Misc      GameChallengeDetailCategory = "misc"
	Pwn       GameChallengeDetailCategory = "pwn"
	Reverse   GameChallengeDetailCategory = "reverse"
	Web       GameChallengeDetailCategory = "web"
)

// Valid indicates whether the value is a known member of the GameChallengeDetailCategory enum.
func (e GameChallengeDetailCategory) Valid() bool {
	switch e {
	case Awd:
		return true
	case Crypto:
		return true
	case Forensics:
		return true
	case Misc:
		return true
	case Pwn:
		return true
	case Reverse:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for GameChallengeDetailType.
const (
	Dynamic GameChallengeDetailType = "dynamic"
	Static  GameChallengeDetailType = "static"
)

// Valid indicates whether the value is a known member of the GameChallengeDetailType enum.
func (e GameChallengeDetailType) Valid() bool {
	switch e {
	case Dynamic:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for GameParticipantEntryStatus.
const (
	GameParticipantEntryStatusAccepted GameParticipantEntryStatus = "accepted"
	GameParticipantEntryStatusPending  GameParticipantEntryStatus = "pending"
	GameParticipantEntryStatusRejected GameParticipantEntryStatus = "rejected"
)

// Valid indicates whether the value is a known member of the GameParticipantEntryStatus enum.
func (e GameParticipantEntryStatus) Valid() bool {
	switch e {
	case GameParticipantEntryStatusAccepted:
		return true
	case GameParticipantEntryStatusPending:
		return true
	case GameParticipantEntryStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for GameParticipationStatus.
const (
	GameParticipationStatusAccepted GameParticipationStatus = "accepted"
	GameParticipationStatusPending  GameParticipationStatus = "pending"
	GameParticipationStatusRejected GameParticipationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the GameParticipationStatus enum.
func (e GameParticipationStatus) Valid() bool {
	switch e {
	case GameParticipationStatusAccepted:
		return true
	case GameParticipationStatusPending:
		return true
	case GameParticipationStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for GameParticipationWriteupStatus.
const (
	GameParticipationWriteupStatusApproved  GameParticipationWriteupStatus = "approved"
	GameParticipationWriteupStatusRejected  GameParticipationWriteupStatus = "rejected"
	GameParticipationWriteupStatusSubmitted GameParticipationWriteupStatus = "submitted"
)

// Valid indicates whether the value is a known member of the GameParticipationWriteupStatus enum.
func (e GameParticipationWriteupStatus) Valid() bool {
	switch e {
	case GameParticipationWriteupStatusApproved:
		return true
	case GameParticipationWriteupStatusRejected:
		return true
	case GameParticipationWriteupStatusSubmitted:
		return true
	default:
		return false
	}
}

// Defines values for GameWriteupStatus.
const (
	GameWriteupStatusApproved  GameWriteupStatus = "approved"
	GameWriteupStatusRejected  GameWriteupStatus = "rejected"
	GameWriteupStatusSubmitted GameWriteupStatus = "submitted"
)

// Valid indicates whether the value is a known member of the GameWriteupStatus enum.
func (e GameWriteupStatus) Valid() bool {
	switch e {
	case GameWriteupStatusApproved:
		return true
	case GameWriteupStatusRejected:
		return true
	case GameWriteupStatusSubmitted:
		return true
	default:
		return false
	}
}

// Defines values for ReviewGameWriteupRequestStatus.
const (
	ReviewGameWriteupRequestStatusApproved ReviewGameWriteupRequestStatus = "approved"
	ReviewGameWriteupRequestStatusRejected ReviewGameWriteupRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ReviewGameWriteupRequestStatus enum.
func (e ReviewGameWriteupRequestStatus) Valid() bool {
	switch e {
	case ReviewGameWriteupRequestStatusApproved:
		return true
	case ReviewGameWriteupRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for SubmitResultBloodType.
const (
	First  SubmitResultBloodType = "first"
	Second SubmitResultBloodType = "second"
	Third  SubmitResultBloodType = "third"
)

// Valid indicates whether the value is a known member of the SubmitResultBloodType enum.
func (e SubmitResultBloodType) Valid() bool {
	switch e {
	case First:
		return true
	case Second:
		return true
	case Third:
		return true
	default:
		return false
	}
}

// Defines values for UpdateGameRequestRegistrationMode.
const (
	AutoAccept UpdateGameRequestRegistrationMode = "auto_accept"
	Review     UpdateGameRequestRegistrationMode = "review"
)

// Valid indicates whether the value is a known member of the UpdateGameRequestRegistrationMode enum.
func (e UpdateGameRequestRegistrationMode) Valid() bool {
	switch e {
	case AutoAccept:
		return true
	case Review:
		return true
	default:
		return false
	}
}

// Defines values for UpdateGameRequestStatus.
const (
	UpdateGameRequestStatusActive UpdateGameRequestStatus = "active"
	UpdateGameRequestStatusDraft  UpdateGameRequestStatus = "draft"
	UpdateGameRequestStatusEnded  UpdateGameRequestStatus = "ended"
)

// Valid indicates whether the value is a known member of the UpdateGameRequestStatus enum.
func (e UpdateGameRequestStatus) Valid() bool {
	switch e {
	case UpdateGameRequestStatusActive:
		return true
	case UpdateGameRequestStatusDraft:
		return true
	case UpdateGameRequestStatusEnded:
		return true
	default:
		return false
	}
}

// Defines values for UpdateParticipationStatusRequestStatus.
const (
	UpdateParticipationStatusRequestStatusAccepted UpdateParticipationStatusRequestStatus = "accepted"
	UpdateParticipationStatusRequestStatusPending  UpdateParticipationStatusRequestStatus = "pending"
	UpdateParticipationStatusRequestStatusRejected UpdateParticipationStatusRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the UpdateParticipationStatusRequestStatus enum.
func (e UpdateParticipationStatusRequestStatus) Valid() bool {
	switch e {
	case UpdateParticipationStatusRequestStatusAccepted:
		return true
	case UpdateParticipationStatusRequestStatusPending:
		return true
	case UpdateParticipationStatusRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for UserInfoRole.
const (
	Admin       UserInfoRole = "admin"
	Judge       UserInfoRole = "judge"
	SuperAdmin  UserInfoRole = "super_admin"
	TeamCaptain UserInfoRole = "team_captain"
	User        UserInfoRole = "user"
)

// Valid indicates whether the value is a known member of the UserInfoRole enum.
func (e UserInfoRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Judge:
		return true
	case SuperAdmin:
		return true
	case TeamCaptain:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for UserInfoStatus.
const (
	Active UserInfoStatus = "active"
	Banned UserInfoStatus = "banned"
)

// Valid indicates whether the value is a known member of the UserInfoStatus enum.
func (e UserInfoStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Banned:
		return true
	default:
		return false
	}
}

// AddChallengeToGameRequest defines model for AddChallengeToGameRequest.
type AddChallengeToGameRequest struct {
	ChallengeId   int  `json:"challenge_id"`
	ScoreOverride *int `json:"score_override,omitempty"`
}

// AdminGameInstanceLease defines model for AdminGameInstanceLease.
type AdminGameInstanceLease struct {
	ChallengeId    int        `json:"challenge_id"`
	ChallengeTitle string     `json:"challenge_title"`
	ExpiresAt      time.Time  `json:"expires_at"`
	GameId         int        `json:"game_id"`
	Id             int        `json:"id"`
	Image          *string    `json:"image,omitempty"`
	IsExpired      bool       `json:"is_expired"`
	LastRenewedAt  time.Time  `json:"last_renewed_at"`
	LaunchUrl      *string    `json:"launch_url,omitempty"`
	Provider       *string    `json:"provider,omitempty"`
	SecondsLeft    int        `json:"seconds_left"`
	StartedAt      time.Time  `json:"started_at"`
	Status         string     `json:"status"`
	StoppedAt      *time.Time `json:"stopped_at,omitempty"`
	TeamId         int        `json:"team_id"`
	TeamName       string     `json:"team_name"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

// AuthSetupStatusResponse defines model for AuthSetupStatusResponse.
type AuthSetupStatusResponse struct {
	BootstrapAdminAvailable bool    `json:"bootstrap_admin_available"`
	DefaultAdminPassword    *string `json:"default_admin_password,omitempty"`
	DefaultAdminUsername    *string `json:"default_admin_username,omitempty"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	Attachments *string              `json:"attachments,omitempty"`
	BaseScore   *int                 `json:"base_score,omitempty"`
	Category    ChallengeCategory    `json:"category"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	DecayRate   *float32             `json:"decay_rate,omitempty"`
	Description *string              `json:"description,omitempty"`
	Difficulty  *ChallengeDifficulty `json:"difficulty,omitempty"`
	Hints       *string              `json:"hints,omitempty"`
	Id          int                  `json:"id"`
	IsVisible   *bool                `json:"is_visible,omitempty"`
	MinScore    *int                 `json:"min_score,omitempty"`
	Title       string               `json:"title"`
	Type        ChallengeType        `json:"type"`
}

// ChallengeCategory defines model for Challenge.Category.
type ChallengeCategory string

// ChallengeDifficulty defines model for Challenge.Difficulty.
type ChallengeDifficulty string

// ChallengeType defines model for Challenge.Type.
type ChallengeType string

// ChallengeInstance defines model for ChallengeInstance.
type ChallengeInstance struct {
	CanRenew      bool                    `json:"can_renew"`
	CanStart      bool                    `json:"can_start"`
	ChallengeId   int                     `json:"challenge_id"`
	Command       *string                 `json:"command,omitempty"`
	ExpiresAt     *time.Time              `json:"expires_at,omitempty"`
	GameId        int                     `json:"game_id"`
	Host          *string                 `json:"host,omitempty"`
	Image         *string                 `json:"image,omitempty"`
	LastRenewedAt *time.Time              `json:"last_renewed_at,omitempty"`
	LaunchUrl     *string                 `json:"launch_url,omitempty"`
	Message       string                  `json:"message"`
	Note          *string                 `json:"note,omitempty"`
	Policy        ChallengeInstancePolicy `json:"policy"`
	Port          *string                 `json:"port,omitempty"`
	Provider      *string                 `json:"provider,omitempty"`
	SecondsLeft   int                     `json:"seconds_left"`
	StartedAt     *time.Time              `json:"started_at,omitempty"`
	Status        ChallengeInstanceStatus `json:"status"`
	TeamId        int                     `json:"team_id"`
}

// ChallengeInstanceStatus defines model for ChallengeInstance.Status.
type ChallengeInstanceStatus string

// ChallengeInstancePolicy defines model for ChallengeInstancePolicy.
type ChallengeInstancePolicy struct {
	ExtensionDurationMinutes int `json:"extension_duration_minutes"`
	LeaseDurationMinutes     int `json:"lease_duration_minutes"`
	RenewalWindowMinutes     int `json:"renewal_window_minutes"`
	TeamActiveLimit          int `json:"team_active_limit"`
}

// CreateChallengeRequest defines model for CreateChallengeRequest.
type CreateChallengeRequest struct {
	Attachments   *string                           `json:"attachments,omitempty"`
	BaseScore     *int                              `json:"base_score,omitempty"`
	Category      CreateChallengeRequestCategory    `json:"category"`
	ContainerSpec *string                           `json:"container_spec,omitempty"`
	DecayRate     *float32                          `json:"decay_rate,omitempty"`
	Description   *string                           `json:"description,omitempty"`
	Difficulty    *CreateChallengeRequestDifficulty `json:"difficulty,omitempty"`
	Flag          string                            `json:"flag"`
	FlagFormat    *string                           `json:"flag_format,omitempty"`
	Hints         *string                           `json:"hints,omitempty"`
	IsVisible     *bool                             `json:"is_visible,omitempty"`
	MaxAttempts   *int                              `json:"max_attempts,omitempty"`
	MinScore      *int                              `json:"min_score,omitempty"`
	Title         string                            `json:"title"`
	Type          *CreateChallengeRequestType       `json:"type,omitempty"`
}

// CreateChallengeRequestCategory defines model for CreateChallengeRequest.Category.
type CreateChallengeRequestCategory string

// CreateChallengeRequestDifficulty defines model for CreateChallengeRequest.Difficulty.
type CreateChallengeRequestDifficulty string

// CreateChallengeRequestType defines model for CreateChallengeRequest.Type.
type CreateChallengeRequestType string

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	Description        *string                            `json:"description,omitempty"`
	Divisions          *[]string                          `json:"divisions,omitempty"`
	EndTime            time.Time                          `json:"end_time"`
	InvitationCode     *string                            `json:"invitation_code,omitempty"`
	IsPublic           *bool                              `json:"is_public,omitempty"`
	MaxTeamMembers     *int                               `json:"max_team_members,omitempty"`
	Name               string                             `json:"name"`
	Notice             *string                            `json:"notice,omitempty"`
	PracticeMode       *bool                              `json:"practice_mode,omitempty"`
	RegistrationMode   *CreateGameRequestRegistrationMode `json:"registration_mode,omitempty"`
	ScoreboardFreezeAt *time.Time                         `json:"scoreboard_freeze_at,omitempty"`
	StartTime          time.Time                          `json:"start_time"`
	WriteupDeadline    *time.Time                         `json:"writeup_deadline,omitempty"`
	WriteupRequired    *bool                              `json:"writeup_required,omitempty"`
}

// CreateGameRequestRegistrationMode defines model for CreateGameRequest.RegistrationMode.
type CreateGameRequestRegistrationMode string

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Game defines model for Game.
type Game struct {
	CreatedAt          *time.Time            `json:"created_at,omitempty"`
	CreatedBy          *int                  `json:"created_by,omitempty"`
	Description        *string               `json:"description,omitempty"`
	Divisions          *[]string             `json:"divisions,omitempty"`
	EndTime            time.Time             `json:"end_time"`
	Id                 int                   `json:"id"`
	InvitationCode     *string               `json:"invitation_code,omitempty"`
	InvitationRequired *bool                 `json:"invitation_required,omitempty"`
	IsPublic           *bool                 `json:"is_public,omitempty"`
	MaxTeamMembers     *int                  `json:"max_team_members,omitempty"`
	Name               string                `json:"name"`
	Notice             *string               `json:"notice,omitempty"`
	PracticeMode       *bool                 `json:"practice_mode,omitempty"`
	RegistrationMode   *GameRegistrationMode `json:"registration_mode,omitempty"`
	ScoreboardFreezeAt *time.Time            `json:"scoreboard_freeze_at,omitempty"`
	StartTime          time.Time             `json:"start_time"`
	Status             GameStatus            `json:"status"`
	WriteupDeadline    *time.Time            `json:"writeup_deadline,omitempty"`
	WriteupRequired    *bool                 `json:"writeup_required,omitempty"`
}

// GameRegistrationMode defines model for Game.RegistrationMode.
type GameRegistrationMode string

// GameStatus defines model for Game.Status.
type GameStatus string

// GameChallengeDetail defines model for GameChallengeDetail.
type GameChallengeDetail struct {
	Attachments     *string                     `json:"attachments,omitempty"`
	BloodTeam       *string                     `json:"blood_team,omitempty"`
	Category        GameChallengeDetailCategory `json:"category"`
	ContainerSpec   *string                     `json:"container_spec,omitempty"`
	Description     *string                     `json:"description,omitempty"`
	Difficulty      *string                     `json:"difficulty,omitempty"`
	Hints           *string                     `json:"hints,omitempty"`
	Id              int                         `json:"id"`
	Score           int                         `json:"score"`
	SecondBloodTeam *string                     `json:"second_blood_team,omitempty"`
	SolveCount      *int                        `json:"solve_count,omitempty"`
	Solved          *bool                       `json:"solved,omitempty"`
	ThirdBloodTeam  *string                     `json:"third_blood_team,omitempty"`
	Title           string                      `json:"title"`
	Type            GameChallengeDetailType     `json:"type"`
}

// GameChallengeDetailCategory defines model for GameChallengeDetail.Category.
type GameChallengeDetailCategory string

// GameChallengeDetailType defines model for GameChallengeDetail.Type.
type GameChallengeDetailType string

// GameParticipantEntry defines model for GameParticipantEntry.
type GameParticipantEntry struct {
	Division   *string                    `json:"division,omitempty"`
	JoinedAt   time.Time                  `json:"joined_at"`
	Score      int                        `json:"score"`
	SolveCount int                        `json:"solve_count"`
	Status     GameParticipantEntryStatus `json:"status"`
	TeamId     int                        `json:"team_id"`
	TeamName   string                     `json:"team_name"`
}

// GameParticipantEntryStatus defines model for GameParticipantEntry.Status.
type GameParticipantEntryStatus string

// GameParticipation defines model for GameParticipation.
type GameParticipation struct {
	Division       *string                  `json:"division,omitempty"`
	Divisions      *[]string                `json:"divisions,omitempty"`
	HasTeam        bool                     `json:"has_team"`
	MissingWriteup *bool                    `json:"missing_writeup,omitempty"`
	Participated   bool                     `json:"participated"`
	Status         *GameParticipationStatus `json:"status,omitempty"`
	Team           *struct {
		Id   int    `json:"id"`
		Name string `json:"name"`
	} `json:"team,omitempty"`
	WriteupDeadline       *time.Time                      `json:"writeup_deadline,omitempty"`
	WriteupDeadlinePassed *bool                           `json:"writeup_deadline_passed,omitempty"`
	WriteupRequired       *bool                           `json:"writeup_required,omitempty"`
	WriteupStatus         *GameParticipationWriteupStatus `json:"writeup_status,omitempty"`
	WriteupSubmitted      *bool                           `json:"writeup_submitted,omitempty"`
}

// GameParticipationStatus defines model for GameParticipation.Status.
type GameParticipationStatus string

// GameParticipationWriteupStatus defines model for GameParticipation.WriteupStatus.
type GameParticipationWriteupStatus string

// GameSubmitFlagRequest defines model for GameSubmitFlagRequest.
type GameSubmitFlagRequest struct {
	Flag   string `json:"flag"`
	TeamId int    `json:"team_id"`
}

// GameWriteup defines model for GameWriteup.
type GameWriteup struct {
	CanSubmit    bool              `json:"can_submit"`
	Content      string            `json:"content"`
	GameId       int               `json:"game_id"`
	ReviewRemark string            `json:"review_remark"`
	ReviewedAt   *time.Time        `json:"reviewed_at,omitempty"`
	ReviewerId   *int              `json:"reviewer_id,omitempty"`
	Status       GameWriteupStatus `json:"status"`
	SubmittedAt  time.Time         `json:"submitted_at"`
	SubmittedBy  int               `json:"submitted_by"`
	TeamId       int               `json:"team_id"`
	TeamName     string            `json:"team_name"`
}

// GameWriteupStatus defines model for GameWriteup.Status.
type GameWriteupStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// JoinGameRequest defines model for JoinGameRequest.
type JoinGameRequest struct {
	InvitationCode *string `json:"invitation_code,omitempty"`
	TeamId         int     `json:"team_id"`
}

// JoinTeamRequest defines model for JoinTeamRequest.
type JoinTeamRequest struct {
	InviteCode string `json:"invite_code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Username Username or email
	Username string `json:"username"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// ReviewGameWriteupRequest defines model for ReviewGameWriteupRequest.
type ReviewGameWriteupRequest struct {
	Remark *string                        `json:"remark,omitempty"`
	Status ReviewGameWriteupRequestStatus `json:"status"`
}

// ReviewGameWriteupRequestStatus defines model for ReviewGameWriteupRequest.Status.
type ReviewGameWriteupRequestStatus string

// Scoreboard defines model for Scoreboard.
type Scoreboard struct {
	Challenges *[]ScoreboardChallengeStat `json:"challenges,omitempty"`
	Division   *string                    `json:"division,omitempty"`
	Divisions  *[]string                  `json:"divisions,omitempty"`
	Entries    []ScoreboardEntry          `json:"entries"`
	FreezeTime *time.Time                 `json:"freeze_time,omitempty"`
	GameId     int                        `json:"game_id"`
	IsFrozen   *bool                      `json:"is_frozen,omitempty"`
}

// ScoreboardChallengeStat defines model for ScoreboardChallengeStat.
type ScoreboardChallengeStat struct {
	BloodTeam       *string `json:"blood_team,omitempty"`
	Category        string  `json:"category"`
	Id              int     `json:"id"`
	Score           int     `json:"score"`
	SecondBloodTeam *string `json:"second_blood_team,omitempty"`
	SolvedCount     int     `json:"solved_count"`
	ThirdBloodTeam  *string `json:"third_blood_team,omitempty"`
	Title           string  `json:"title"`
}

// ScoreboardEntry defines model for ScoreboardEntry.
type ScoreboardEntry struct {
	LastSolve  *time.Time `json:"last_solve,omitempty"`
	Rank       int        `json:"rank"`
	Score      int        `json:"score"`
	SolveCount int        `json:"solve_count"`
	TeamId     int        `json:"team_id"`
	TeamName   string     `json:"team_name"`
}

// SubmitFlagRequest defines model for SubmitFlagRequest.
type SubmitFlagRequest struct {
	Flag   string `json:"flag"`
	GameId int    `json:"game_id"`
}

// SubmitGameWriteupRequest defines model for SubmitGameWriteupRequest.
type SubmitGameWriteupRequest struct {
	Content string `json:"content"`
}

// SubmitResult defines model for SubmitResult.
type SubmitResult struct {
	BloodType  *SubmitResultBloodType `json:"blood_type,omitempty"`
	Correct    bool                   `json:"correct"`
	IsPractice *bool                  `json:"is_practice,omitempty"`
	Message    string                 `json:"message"`
	Score      *int                   `json:"score,omitempty"`
}

// SubmitResultBloodType defines model for SubmitResult.BloodType.
type SubmitResultBloodType string

// Team defines model for Team.
type Team struct {
	CreatedAt  *time.Time       `json:"created_at,omitempty"`
	Id         int              `json:"id"`
	InviteCode string           `json:"invite_code"`
	Lock       *TeamLockSummary `json:"lock,omitempty"`
	Members    *[]TeamMember    `json:"members,omitempty"`
	Name       string           `json:"name"`
}

// TeamLockGame defines model for TeamLockGame.
type TeamLockGame struct {
	EndTime   time.Time `json:"end_time"`
	GameId    int       `json:"game_id"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"start_time"`
}

// TeamLockSummary defines model for TeamLockSummary.
type TeamLockSummary struct {
	Games  []TeamLockGame `json:"games"`
	Locked bool           `json:"locked"`
	Reason *string        `json:"reason,omitempty"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	Id     int    `json:"id"`
	Role   string `json:"role"`
	TeamId int    `json:"team_id"`
	UserId int    `json:"user_id"`
}

// UpdateChallengeRequest defines model for UpdateChallengeRequest.
type UpdateChallengeRequest struct {
	Attachments   *string  `json:"attachments,omitempty"`
	BaseScore     *int     `json:"base_score,omitempty"`
	Category      *string  `json:"category,omitempty"`
	ContainerSpec *string  `json:"container_spec,omitempty"`
	DecayRate     *float32 `json:"decay_rate,omitempty"`
	Description   *string  `json:"description,omitempty"`
	Difficulty    *string  `json:"difficulty,omitempty"`
	Flag          *string  `json:"flag,omitempty"`
	FlagFormat    *string  `json:"flag_format,omitempty"`
	Hints         *string  `json:"hints,omitempty"`
	IsVisible     *bool    `json:"is_visible,omitempty"`
	MaxAttempts   *int     `json:"max_attempts,omitempty"`
	MinScore      *int     `json:"min_score,omitempty"`
	Title         *string  `json:"title,omitempty"`
	Type          *string  `json:"type,omitempty"`
}

// UpdateGameRequest defines model for UpdateGameRequest.
type UpdateGameRequest struct {
	Description        *string                            `json:"description,omitempty"`
	Divisions          *[]string                          `json:"divisions,omitempty"`
	EndTime            *time.Time                         `json:"end_time,omitempty"`
	InvitationCode     *string                            `json:"invitation_code,omitempty"`
	IsPublic           *bool                              `json:"is_public,omitempty"`
	MaxTeamMembers     *int                               `json:"max_team_members,omitempty"`
	Name               *string                            `json:"name,omitempty"`
	Notice             *string                            `json:"notice,omitempty"`
	PracticeMode       *bool                              `json:"practice_mode,omitempty"`
	RegistrationMode   *UpdateGameRequestRegistrationMode `json:"registration_mode,omitempty"`
	ScoreboardFreezeAt *time.Time                         `json:"scoreboard_freeze_at,omitempty"`
	StartTime          *time.Time                         `json:"start_time,omitempty"`
	Status             *UpdateGameRequestStatus           `json:"status,omitempty"`
	WriteupDeadline    *time.Time                         `json:"writeup_deadline,omitempty"`
	WriteupRequired    *bool                              `json:"writeup_required,omitempty"`
}

// UpdateGameRequestRegistrationMode defines model for UpdateGameRequest.RegistrationMode.
type UpdateGameRequestRegistrationMode string

// UpdateGameRequestStatus defines model for UpdateGameRequest.Status.
type UpdateGameRequestStatus string

// UpdateParticipationStatusRequest defines model for UpdateParticipationStatusRequest.
type UpdateParticipationStatusRequest struct {
	Division *string                                `json:"division,omitempty"`
	Status   UpdateParticipationStatusRequestStatus `json:"status"`
}

// UpdateParticipationStatusRequestStatus defines model for UpdateParticipationStatusRequest.Status.
type UpdateParticipationStatusRequestStatus string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	CreatedAt *time.Time     `json:"created_at,omitempty"`
	Email     string         `json:"email"`
	Id        int            `json:"id"`
	Role      UserInfoRole   `json:"role"`
	Status    UserInfoStatus `json:"status"`
	Username  string         `json:"username"`
}

// UserInfoRole defines model for UserInfo.Role.
type UserInfoRole string

// UserInfoStatus defines model for UserInfo.Status.
type UserInfoStatus string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ImportAdminGamePackageMultipartBody defines parameters for ImportAdminGamePackage.
type ImportAdminGamePackageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListChallengesParams defines parameters for ListChallenges.
type ListChallengesParams struct {
	Category   *string `form:"category,omitempty" json:"category,omitempty"`
	ShowHidden *bool   `form:"show_hidden,omitempty" json:"show_hidden,omitempty"`
}

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	All *bool `form:"all,omitempty" json:"all,omitempty"`
}

// GetScoreboardParams defines parameters for GetScoreboard.
type GetScoreboardParams struct {
	Division *string `form:"division,omitempty" json:"division,omitempty"`
}

// ImportAdminGamePackageMultipartRequestBody defines body for ImportAdminGamePackage for multipart/form-data ContentType.
type ImportAdminGamePackageMultipartRequestBody ImportAdminGamePackageMultipartBody

// UpdateAdminGameWriteupJSONRequestBody defines body for UpdateAdminGameWriteup for application/json ContentType.
type UpdateAdminGameWriteupJSONRequestBody = ReviewGameWriteupRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateChallengeJSONRequestBody defines body for CreateChallenge for application/json ContentType.
type CreateChallengeJSONRequestBody = CreateChallengeRequest

// UpdateChallengeJSONRequestBody defines body for UpdateChallenge for application/json ContentType.
type UpdateChallengeJSONRequestBody = UpdateChallengeRequest

// SubmitChallengeFlagJSONRequestBody defines body for SubmitChallengeFlag for application/json ContentType.
type SubmitChallengeFlagJSONRequestBody = SubmitFlagRequest

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// UpdateGameJSONRequestBody defines body for UpdateGame for application/json ContentType.
type UpdateGameJSONRequestBody = UpdateGameRequest

// AddChallengeToGameJSONRequestBody defines body for AddChallengeToGame for application/json ContentType.
type AddChallengeToGameJSONRequestBody = AddChallengeToGameRequest

// SubmitGameFlagJSONRequestBody defines body for SubmitGameFlag for application/json ContentType.
type SubmitGameFlagJSONRequestBody = GameSubmitFlagRequest

// JoinGameJSONRequestBody defines body for JoinGame for application/json ContentType.
type JoinGameJSONRequestBody = JoinGameRequest

// LeaveGameJSONRequestBody defines body for LeaveGame for application/json ContentType.
type LeaveGameJSONRequestBody = JoinGameRequest

// UpdateGameParticipantJSONRequestBody defines body for UpdateGameParticipant for application/json ContentType.
type UpdateGameParticipantJSONRequestBody = UpdateParticipationStatusRequest

// SubmitGameWriteupJSONRequestBody defines body for SubmitGameWriteup for application/json ContentType.
type SubmitGameWriteupJSONRequestBody = SubmitGameWriteupRequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// JoinTeamJSONRequestBody defines body for JoinTeam for application/json ContentType.
type JoinTeamJSONRequestBody = JoinTeamRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Import a game package (admin)
	// (POST /api/admin/games/import)
	ImportAdminGamePackage(c *gin.Context)
	// Delete a game and its game-scoped relations (admin)
	// (DELETE /api/admin/games/{id})
	DeleteAdminGame(c *gin.Context, id int)
	// Get full mounted challenges for management (admin)
	// (GET /api/admin/games/{id}/challenges)
	GetAdminGameChallenges(c *gin.Context, id int)
	// Export a game package (admin)
	// (POST /api/admin/games/{id}/export)
	ExportAdminGamePackage(c *gin.Context, id int)
	// List current instance leases for a game (admin)
	// (GET /api/admin/games/{id}/instances)
	GetAdminGameInstances(c *gin.Context, id int)
	// List game writeups for review (admin)
	// (GET /api/admin/games/{id}/writeups)
	GetAdminGameWriteups(c *gin.Context, id int)
	// Review a game writeup (admin)
	// (PUT /api/admin/games/{id}/writeups/{teamId})
	UpdateAdminGameWriteup(c *gin.Context, id int, teamId int)
	// Login with username or email
	// (POST /api/auth/login)
	Login(c *gin.Context)
	// Invalidate session
	// (POST /api/auth/logout)
	Logout(c *gin.Context)
	// Get current user info
	// (GET /api/auth/me)
	GetMe(c *gin.Context)
	// Register a new user
	// (POST /api/auth/register)
	Register(c *gin.Context)
	// Get auth bootstrap setup status
	// (GET /api/auth/setup-status)
	GetAuthSetupStatus(c *gin.Context)
	// List challenges
	// (GET /api/challenges)
	ListChallenges(c *gin.Context, params ListChallengesParams)
	// Create a challenge (admin)
	// (POST /api/challenges)
	CreateChallenge(c *gin.Context)
	// Delete a challenge (admin)
	// (DELETE /api/challenges/{id})
	DeleteChallenge(c *gin.Context, id int)
	// Get a challenge
	// (GET /api/challenges/{id})
	GetChallenge(c *gin.Context, id int)
	// Update a challenge (admin)
	// (PUT /api/challenges/{id})
	UpdateChallenge(c *gin.Context, id int)
	// Submit flag for standalone challenge
	// (POST /api/challenges/{id}/submit)
	SubmitChallengeFlag(c *gin.Context, id int)
	// List games
	// (GET /api/games)
	ListGames(c *gin.Context, params ListGamesParams)
	// Create a game (admin)
	// (POST /api/games)
	CreateGame(c *gin.Context)
	// Get a game
	// (GET /api/games/{id})
	GetGame(c *gin.Context, id int)
	// Update a game (admin)
	// (PUT /api/games/{id})
	UpdateGame(c *gin.Context, id int)
	// Get challenges in a game
	// (GET /api/games/{id}/challenges)
	GetGameChallenges(c *gin.Context, id int)
	// Add a challenge to a game (admin)
	// (POST /api/games/{id}/challenges)
	AddChallengeToGame(c *gin.Context, id int)
	// Remove a challenge from a game (admin)
	// (DELETE /api/games/{id}/challenges/{challengeId})
	RemoveChallengeFromGame(c *gin.Context, id int, challengeId int)
	// Destroy current team challenge instance lease
	// (DELETE /api/games/{id}/challenges/{challengeId}/instance)
	DestroyChallengeInstance(c *gin.Context, id int, challengeId int)
	// Get current team challenge instance lease
	// (GET /api/games/{id}/challenges/{challengeId}/instance)
	GetChallengeInstance(c *gin.Context, id int, challengeId int)
	// Start or renew current team challenge instance lease
	// (POST /api/games/{id}/challenges/{challengeId}/instance)
	EnsureChallengeInstance(c *gin.Context, id int, challengeId int)
	// Submit flag for a challenge in a game
	// (POST /api/games/{id}/challenges/{challengeId}/submit)
	SubmitGameFlag(c *gin.Context, id int, challengeId int)
	// Join a game with a team
	// (POST /api/games/{id}/join)
	JoinGame(c *gin.Context, id int)
	// Leave a game
	// (DELETE /api/games/{id}/leave)
	LeaveGame(c *gin.Context, id int)
	// Get game participants (admin)
	// (GET /api/games/{id}/participants)
	GetGameParticipants(c *gin.Context, id int)
	// Remove participant from a game (admin)
	// (DELETE /api/games/{id}/participants/{teamId})
	DeleteGameParticipant(c *gin.Context, id int, teamId int)
	// Update participant status in a game (admin)
	// (PUT /api/games/{id}/participants/{teamId})
	UpdateGameParticipant(c *gin.Context, id int, teamId int)
	// Get my participation status in a game
	// (GET /api/games/{id}/participation)
	GetGameParticipation(c *gin.Context, id int)
	// Get game scoreboard
	// (GET /api/games/{id}/scoreboard)
	GetScoreboard(c *gin.Context, id int, params GetScoreboardParams)
	// Get my game writeup
	// (GET /api/games/{id}/writeup)
	GetGameWriteup(c *gin.Context, id int)
	// Submit or update my game writeup
	// (PUT /api/games/{id}/writeup)
	SubmitGameWriteup(c *gin.Context, id int)
	// Health check
	// (GET /api/healthz)
	Healthz(c *gin.Context)
	// Create a team
	// (POST /api/teams)
	CreateTeam(c *gin.Context)
	// Join a team by invite code
	// (POST /api/teams/join)
	JoinTeam(c *gin.Context)
	// Leave current team
	// (POST /api/teams/leave)
	LeaveTeam(c *gin.Context)
	// Get my team
	// (GET /api/teams/my)
	GetMyTeam(c *gin.Context)
	// Remove a team member (captain only)
	// (DELETE /api/teams/{teamId}/members/{memberId})
	RemoveTeamMember(c *gin.Context, teamId int, memberId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ImportAdminGamePackage operation middleware
func (siw *ServerInterfaceWrapper) ImportAdminGamePackage(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportAdminGamePackage(c)
}

// DeleteAdminGame operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminGame(c, id)
}

// GetAdminGameChallenges operation middleware
func (siw *ServerInterfaceWrapper) GetAdminGameChallenges(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminGameChallenges(c, id)
}

// ExportAdminGamePackage operation middleware
func (siw *ServerInterfaceWrapper) ExportAdminGamePackage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportAdminGamePackage(c, id)
}

// GetAdminGameInstances operation middleware
func (siw *ServerInterfaceWrapper) GetAdminGameInstances(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminGameInstances(c, id)
}

// GetAdminGameWriteups operation middleware
func (siw *ServerInterfaceWrapper) GetAdminGameWriteups(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminGameWriteups(c, id)
}

// UpdateAdminGameWriteup operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminGameWriteup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "teamId" -------------
	var teamId int

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAdminGameWriteup(c, id, teamId)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// GetAuthSetupStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSetupStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthSetupStatus(c)
}

// ListChallenges operation middleware
func (siw *ServerInterfaceWrapper) ListChallenges(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChallengesParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "show_hidden" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "show_hidden", c.Request.URL.Query(), &params.ShowHidden, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter show_hidden: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChallenges(c, params)
}

// CreateChallenge operation middleware
func (siw *ServerInterfaceWrapper) CreateChallenge(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChallenge(c)
}

// DeleteChallenge operation middleware
func (siw *ServerInterfaceWrapper) DeleteChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChallenge(c, id)
}

// GetChallenge operation middleware
func (siw *ServerInterfaceWrapper) GetChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallenge(c, id)
}

// UpdateChallenge operation middleware
func (siw *ServerInterfaceWrapper) UpdateChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateChallenge(c, id)
}

// SubmitChallengeFlag operation middleware
func (siw *ServerInterfaceWrapper) SubmitChallengeFlag(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitChallengeFlag(c, id)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "all" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "all", c.Request.URL.Query(), &params.All, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter all: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGames(c, params)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGame(c)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGame(c, id)
}

// UpdateGame operation middleware
func (siw *ServerInterfaceWrapper) UpdateGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGame(c, id)
}

// GetGameChallenges operation middleware
func (siw *ServerInterfaceWrapper) GetGameChallenges(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameChallenges(c, id)
}

// AddChallengeToGame operation middleware
func (siw *ServerInterfaceWrapper) AddChallengeToGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddChallengeToGame(c, id)
}

// RemoveChallengeFromGame operation middleware
func (siw *ServerInterfaceWrapper) RemoveChallengeFromGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveChallengeFromGame(c, id, challengeId)
}

// DestroyChallengeInstance operation middleware
func (siw *ServerInterfaceWrapper) DestroyChallengeInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DestroyChallengeInstance(c, id, challengeId)
}

// GetChallengeInstance operation middleware
func (siw *ServerInterfaceWrapper) GetChallengeInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallengeInstance(c, id, challengeId)
}

// EnsureChallengeInstance operation middleware
func (siw *ServerInterfaceWrapper) EnsureChallengeInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnsureChallengeInstance(c, id, challengeId)
}

// SubmitGameFlag operation middleware
func (siw *ServerInterfaceWrapper) SubmitGameFlag(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "challengeId" -------------
	var challengeId int

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", c.Param("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter challengeId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitGameFlag(c, id, challengeId)
}

// JoinGame operation middleware
func (siw *ServerInterfaceWrapper) JoinGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinGame(c, id)
}

// LeaveGame operation middleware
func (siw *ServerInterfaceWrapper) LeaveGame(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveGame(c, id)
}

// GetGameParticipants operation middleware
func (siw *ServerInterfaceWrapper) GetGameParticipants(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameParticipants(c, id)
}

// DeleteGameParticipant operation middleware
func (siw *ServerInterfaceWrapper) DeleteGameParticipant(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "teamId" -------------
	var teamId int

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGameParticipant(c, id, teamId)
}

// UpdateGameParticipant operation middleware
func (siw *ServerInterfaceWrapper) UpdateGameParticipant(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "teamId" -------------
	var teamId int

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGameParticipant(c, id, teamId)
}

// GetGameParticipation operation middleware
func (siw *ServerInterfaceWrapper) GetGameParticipation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameParticipation(c, id)
}

// GetScoreboard operation middleware
func (siw *ServerInterfaceWrapper) GetScoreboard(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetScoreboardParams

	// ------------- Optional query parameter "division" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "division", c.Request.URL.Query(), &params.Division, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter division: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetScoreboard(c, id, params)
}

// GetGameWriteup operation middleware
func (siw *ServerInterfaceWrapper) GetGameWriteup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameWriteup(c, id)
}

// SubmitGameWriteup operation middleware
func (siw *ServerInterfaceWrapper) SubmitGameWriteup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitGameWriteup(c, id)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTeam(c)
}

// JoinTeam operation middleware
func (siw *ServerInterfaceWrapper) JoinTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinTeam(c)
}

// LeaveTeam operation middleware
func (siw *ServerInterfaceWrapper) LeaveTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveTeam(c)
}

// GetMyTeam operation middleware
func (siw *ServerInterfaceWrapper) GetMyTeam(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyTeam(c)
}

// RemoveTeamMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTeamMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamId" -------------
	var teamId int

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveTeamMember(c, teamId, memberId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/admin/games/import", wrapper.ImportAdminGamePackage)
	router.DELETE(options.BaseURL+"/api/admin/games/:id", wrapper.DeleteAdminGame)
	router.GET(options.BaseURL+"/api/admin/games/:id/challenges", wrapper.GetAdminGameChallenges)
	router.POST(options.BaseURL+"/api/admin/games/:id/export", wrapper.ExportAdminGamePackage)
	router.GET(options.BaseURL+"/api/admin/games/:id/instances", wrapper.GetAdminGameInstances)
	router.GET(options.BaseURL+"/api/admin/games/:id/writeups", wrapper.GetAdminGameWriteups)
	router.PUT(options.BaseURL+"/api/admin/games/:id/writeups/:teamId", wrapper.UpdateAdminGameWriteup)
	router.POST(options.BaseURL+"/api/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/api/auth/setup-status", wrapper.GetAuthSetupStatus)
	router.GET(options.BaseURL+"/api/challenges", wrapper.ListChallenges)
	router.POST(options.BaseURL+"/api/challenges", wrapper.CreateChallenge)
	router.DELETE(options.BaseURL+"/api/challenges/:id", wrapper.DeleteChallenge)
	router.GET(options.BaseURL+"/api/challenges/:id", wrapper.GetChallenge)
	router.PUT(options.BaseURL+"/api/challenges/:id", wrapper.UpdateChallenge)
	router.POST(options.BaseURL+"/api/challenges/:id/submit", wrapper.SubmitChallengeFlag)
	router.GET(options.BaseURL+"/api/games", wrapper.ListGames)
	router.POST(options.BaseURL+"/api/games", wrapper.CreateGame)
	router.GET(options.BaseURL+"/api/games/:id", wrapper.GetGame)
	router.PUT(options.BaseURL+"/api/games/:id", wrapper.UpdateGame)
	router.GET(options.BaseURL+"/api/games/:id/challenges", wrapper.GetGameChallenges)
	router.POST(options.BaseURL+"/api/games/:id/challenges", wrapper.AddChallengeToGame)
	router.DELETE(options.BaseURL+"/api/games/:id/challenges/:challengeId", wrapper.RemoveChallengeFromGame)
	router.DELETE(options.BaseURL+"/api/games/:id/challenges/:challengeId/instance", wrapper.DestroyChallengeInstance)
	router.GET(options.BaseURL+"/api/games/:id/challenges/:challengeId/instance", wrapper.GetChallengeInstance)
	router.POST(options.BaseURL+"/api/games/:id/challenges/:challengeId/instance", wrapper.EnsureChallengeInstance)
	router.POST(options.BaseURL+"/api/games/:id/challenges/:challengeId/submit", wrapper.SubmitGameFlag)
	router.POST(options.BaseURL+"/api/games/:id/join", wrapper.JoinGame)
	router.DELETE(options.BaseURL+"/api/games/:id/leave", wrapper.LeaveGame)
	router.GET(options.BaseURL+"/api/games/:id/participants", wrapper.GetGameParticipants)
	router.DELETE(options.BaseURL+"/api/games/:id/participants/:teamId", wrapper.DeleteGameParticipant)
	router.PUT(options.BaseURL+"/api/games/:id/participants/:teamId", wrapper.UpdateGameParticipant)
	router.GET(options.BaseURL+"/api/games/:id/participation", wrapper.GetGameParticipation)
	router.GET(options.BaseURL+"/api/games/:id/scoreboard", wrapper.GetScoreboard)
	router.GET(options.BaseURL+"/api/games/:id/writeup", wrapper.GetGameWriteup)
	router.PUT(options.BaseURL+"/api/games/:id/writeup", wrapper.SubmitGameWriteup)
	router.GET(options.BaseURL+"/api/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/api/teams", wrapper.CreateTeam)
	router.POST(options.BaseURL+"/api/teams/join", wrapper.JoinTeam)
	router.POST(options.BaseURL+"/api/teams/leave", wrapper.LeaveTeam)
	router.GET(options.BaseURL+"/api/teams/my", wrapper.GetMyTeam)
	router.DELETE(options.BaseURL+"/api/teams/:teamId/members/:memberId", wrapper.RemoveTeamMember)
}
