/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/healthz": {
    /** Health check */
    get: operations["healthz"];
  };
  "/api/auth/register": {
    /** Register a new user */
    post: operations["register"];
  };
  "/api/auth/login": {
    /** Login with username or email */
    post: operations["login"];
  };
  "/api/auth/logout": {
    /** Invalidate session */
    post: operations["logout"];
  };
  "/api/auth/me": {
    /** Get current user info */
    get: operations["getMe"];
  };
  "/api/teams": {
    /** Create a team */
    post: operations["createTeam"];
  };
  "/api/teams/my": {
    /** Get my team */
    get: operations["getMyTeam"];
  };
  "/api/teams/join": {
    /** Join a team by invite code */
    post: operations["joinTeam"];
  };
  "/api/teams/leave": {
    /** Leave current team */
    post: operations["leaveTeam"];
  };
  "/api/teams/{teamId}/members/{memberId}": {
    /** Remove a team member (captain only) */
    delete: operations["removeTeamMember"];
  };
  "/api/challenges": {
    /** List challenges */
    get: operations["listChallenges"];
    /** Create a challenge (admin) */
    post: operations["createChallenge"];
  };
  "/api/challenges/{id}": {
    /** Get a challenge */
    get: operations["getChallenge"];
    /** Update a challenge (admin) */
    put: operations["updateChallenge"];
    /** Delete a challenge (admin) */
    delete: operations["deleteChallenge"];
  };
  "/api/challenges/{id}/submit": {
    /** Submit flag for standalone challenge */
    post: operations["submitChallengeFlag"];
  };
  "/api/games": {
    /** List games */
    get: operations["listGames"];
    /** Create a game (admin) */
    post: operations["createGame"];
  };
  "/api/games/{id}": {
    /** Get a game */
    get: operations["getGame"];
    /** Update a game (admin) */
    put: operations["updateGame"];
  };
  "/api/games/{id}/join": {
    /** Join a game with a team */
    post: operations["joinGame"];
  };
  "/api/games/{id}/participation": {
    /** Get my participation status in a game */
    get: operations["getGameParticipation"];
  };
  "/api/games/{id}/leave": {
    /** Leave a game */
    delete: operations["leaveGame"];
  };
  "/api/games/{id}/challenges": {
    /** Get challenges in a game */
    get: operations["getGameChallenges"];
    /** Add a challenge to a game (admin) */
    post: operations["addChallengeToGame"];
  };
  "/api/games/{id}/challenges/{challengeId}": {
    /** Remove a challenge from a game (admin) */
    delete: operations["removeChallengeFromGame"];
  };
  "/api/games/{id}/challenges/{challengeId}/submit": {
    /** Submit flag for a challenge in a game */
    post: operations["submitGameFlag"];
  };
  "/api/games/{id}/scoreboard": {
    /** Get game scoreboard */
    get: operations["getScoreboard"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: string;
    };
    MessageResponse: {
      message: string;
    };
    UserInfo: {
      id: number;
      username: string;
      email: string;
      /** @enum {string} */
      role: "user" | "team_captain" | "judge" | "admin" | "super_admin";
      /** @enum {string} */
      status: "active" | "banned";
      /** Format: date-time */
      created_at?: string;
    };
    RegisterRequest: {
      username: string;
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** @description Username or email */
      username: string;
      password: string;
    };
    AuthResponse: {
      token: string;
      user: components["schemas"]["UserInfo"];
    };
    Team: {
      id: number;
      name: string;
      invite_code: string;
      /** Format: date-time */
      created_at?: string;
      members?: components["schemas"]["TeamMember"][];
    };
    TeamMember: {
      id: number;
      user_id: number;
      team_id: number;
      role: string;
    };
    CreateTeamRequest: {
      name: string;
    };
    JoinTeamRequest: {
      invite_code: string;
    };
    Challenge: {
      id: number;
      title: string;
      description?: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type: "static" | "dynamic";
      /** @enum {string} */
      difficulty?: "easy" | "medium" | "hard";
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      hints?: string;
      attachments?: string;
      is_visible?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    CreateChallengeRequest: {
      title: string;
      description?: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type?: "static" | "dynamic";
      /** @enum {string} */
      difficulty?: "easy" | "medium" | "hard";
      flag: string;
      flag_format?: string;
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      max_attempts?: number;
      hints?: string;
      attachments?: string;
      container_spec?: string;
      is_visible?: boolean;
    };
    UpdateChallengeRequest: {
      title?: string;
      description?: string;
      category?: string;
      type?: string;
      difficulty?: string;
      flag?: string;
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      is_visible?: boolean;
    };
    SubmitFlagRequest: {
      flag: string;
      game_id: number;
    };
    SubmitResult: {
      correct: boolean;
      score?: number;
      /** @enum {string} */
      blood_type?: "first" | "second" | "third";
      message: string;
    };
    Game: {
      id: number;
      name: string;
      description?: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** @enum {string} */
      status: "draft" | "active" | "ended";
      is_public?: boolean;
      created_by?: number;
      /** Format: date-time */
      created_at?: string;
    };
    CreateGameRequest: {
      name: string;
      description?: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      is_public?: boolean;
    };
    UpdateGameRequest: {
      name?: string;
      description?: string;
      /** Format: date-time */
      start_time?: string;
      /** Format: date-time */
      end_time?: string;
      /** @enum {string} */
      status?: "draft" | "active" | "ended";
      is_public?: boolean;
    };
    AddChallengeToGameRequest: {
      challenge_id: number;
      score_override?: number;
    };
    GameChallengeDetail: {
      id: number;
      title: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type: "static" | "dynamic";
      difficulty?: string;
      score: number;
      solved?: boolean;
      solve_count?: number;
      blood_team?: string;
    };
    JoinGameRequest: {
      team_id: number;
    };
    GameSubmitFlagRequest: {
      flag: string;
      team_id: number;
    };
    ScoreboardEntry: {
      rank: number;
      team_id: number;
      team_name: string;
      score: number;
      solve_count: number;
      /** Format: date-time */
      last_solve?: string;
    };
    Scoreboard: {
      game_id: number;
      entries: components["schemas"]["ScoreboardEntry"][];
    };
    GameParticipation: {
      has_team: boolean;
      participated: boolean;
      /** @enum {string} */
      status?: "pending" | "accepted" | "rejected";
      team?: {
        id: number;
        name: string;
      };
    };
    HealthResponse: {
      status: string;
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health check */
  healthz: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Register a new user */
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Registered and logged in */
      201: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Username or email already exists */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Login with username or email */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Invalidate session */
  logout: {
    responses: {
      /** @description Logged out */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Get current user info */
  getMe: {
    responses: {
      /** @description Current user */
      200: {
        content: {
          "application/json": {
            user: components["schemas"]["UserInfo"];
          };
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create a team */
  createTeam: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamRequest"];
      };
    };
    responses: {
      /** @description Team created */
      201: {
        content: {
          "application/json": {
            team: components["schemas"]["Team"];
          };
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get my team */
  getMyTeam: {
    responses: {
      /** @description My team */
      200: {
        content: {
          "application/json": {
            team: components["schemas"]["Team"];
          };
        };
      };
      /** @description Not in any team */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Join a team by invite code */
  joinTeam: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinTeamRequest"];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Already in a team */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Leave current team */
  leaveTeam: {
    responses: {
      /** @description Left */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Cannot leave */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Remove a team member (captain only) */
  removeTeamMember: {
    parameters: {
      path: {
        teamId: number;
        memberId: number;
      };
    };
    responses: {
      /** @description Removed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Cannot remove */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List challenges */
  listChallenges: {
    parameters: {
      query?: {
        category?: string;
        show_hidden?: boolean;
      };
    };
    responses: {
      /** @description Challenge list */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"][];
        };
      };
    };
  };
  /** Create a challenge (admin) */
  createChallenge: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateChallengeRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
    };
  };
  /** Get a challenge */
  getChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Challenge */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update a challenge (admin) */
  updateChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateChallengeRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
    };
  };
  /** Delete a challenge (admin) */
  deleteChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Submit flag for standalone challenge */
  submitChallengeFlag: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitFlagRequest"];
      };
    };
    responses: {
      /** @description Correct flag */
      200: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
      /** @description Wrong flag */
      403: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
    };
  };
  /** List games */
  listGames: {
    parameters: {
      query?: {
        all?: boolean;
      };
    };
    responses: {
      /** @description Game list */
      200: {
        content: {
          "application/json": components["schemas"]["Game"][];
        };
      };
    };
  };
  /** Create a game (admin) */
  createGame: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
    };
  };
  /** Get a game */
  getGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Game */
      200: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update a game (admin) */
  updateGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGameRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
    };
  };
  /** Join a game with a team */
  joinGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinGameRequest"];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Already joined */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get my participation status in a game */
  getGameParticipation: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Participation status */
      200: {
        content: {
          "application/json": components["schemas"]["GameParticipation"];
        };
      };
      /** @description Game not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Leave a game */
  leaveGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinGameRequest"];
      };
    };
    responses: {
      /** @description Left */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Get challenges in a game */
  getGameChallenges: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Challenge list */
      200: {
        content: {
          "application/json": components["schemas"]["GameChallengeDetail"][];
        };
      };
    };
  };
  /** Add a challenge to a game (admin) */
  addChallengeToGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddChallengeToGameRequest"];
      };
    };
    responses: {
      /** @description Added */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Remove a challenge from a game (admin) */
  removeChallengeFromGame: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    responses: {
      /** @description Removed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Submit flag for a challenge in a game */
  submitGameFlag: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GameSubmitFlagRequest"];
      };
    };
    responses: {
      /** @description Correct */
      200: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
      /** @description Wrong flag */
      403: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
    };
  };
  /** Get game scoreboard */
  getScoreboard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Scoreboard */
      200: {
        content: {
          "application/json": components["schemas"]["Scoreboard"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
