/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/healthz": {
    /** Health check */
    get: operations["healthz"];
  };
  "/api/auth/register": {
    /** Register a new user */
    post: operations["register"];
  };
  "/api/auth/login": {
    /** Login with username or email */
    post: operations["login"];
  };
  "/api/auth/setup-status": {
    /** Get auth bootstrap setup status */
    get: operations["getAuthSetupStatus"];
  };
  "/api/auth/logout": {
    /** Invalidate session */
    post: operations["logout"];
  };
  "/api/auth/me": {
    /** Get current user info */
    get: operations["getMe"];
  };
  "/api/teams": {
    /** Create a team */
    post: operations["createTeam"];
  };
  "/api/teams/my": {
    /** Get my team */
    get: operations["getMyTeam"];
  };
  "/api/teams/join": {
    /** Join a team by invite code */
    post: operations["joinTeam"];
  };
  "/api/teams/leave": {
    /** Leave current team */
    post: operations["leaveTeam"];
  };
  "/api/teams/{teamId}/members/{memberId}": {
    /** Remove a team member (captain only) */
    delete: operations["removeTeamMember"];
  };
  "/api/challenges": {
    /** List challenges */
    get: operations["listChallenges"];
    /** Create a challenge (admin) */
    post: operations["createChallenge"];
  };
  "/api/challenges/{id}": {
    /** Get a challenge */
    get: operations["getChallenge"];
    /** Update a challenge (admin) */
    put: operations["updateChallenge"];
    /** Delete a challenge (admin) */
    delete: operations["deleteChallenge"];
  };
  "/api/challenges/{id}/submit": {
    /** Submit flag for standalone challenge */
    post: operations["submitChallengeFlag"];
  };
  "/api/games": {
    /** List games */
    get: operations["listGames"];
    /** Create a game (admin) */
    post: operations["createGame"];
  };
  "/api/games/{id}": {
    /** Get a game */
    get: operations["getGame"];
    /** Update a game (admin) */
    put: operations["updateGame"];
  };
  "/api/games/{id}/join": {
    /** Join a game with a team */
    post: operations["joinGame"];
  };
  "/api/games/{id}/participation": {
    /** Get my participation status in a game */
    get: operations["getGameParticipation"];
  };
  "/api/games/{id}/writeup": {
    /** Get my game writeup */
    get: operations["getGameWriteup"];
    /** Submit or update my game writeup */
    put: operations["submitGameWriteup"];
  };
  "/api/games/{id}/leave": {
    /** Leave a game */
    delete: operations["leaveGame"];
  };
  "/api/games/{id}/challenges": {
    /** Get challenges in a game */
    get: operations["getGameChallenges"];
    /** Add a challenge to a game (admin) */
    post: operations["addChallengeToGame"];
  };
  "/api/games/{id}/challenges/{challengeId}": {
    /** Remove a challenge from a game (admin) */
    delete: operations["removeChallengeFromGame"];
  };
  "/api/games/{id}/challenges/{challengeId}/submit": {
    /** Submit flag for a challenge in a game */
    post: operations["submitGameFlag"];
  };
  "/api/games/{id}/challenges/{challengeId}/instance": {
    /** Get current team challenge instance lease */
    get: operations["getChallengeInstance"];
    /** Start or renew current team challenge instance lease */
    post: operations["ensureChallengeInstance"];
    /** Destroy current team challenge instance lease */
    delete: operations["destroyChallengeInstance"];
  };
  "/api/games/{id}/scoreboard": {
    /** Get game scoreboard */
    get: operations["getScoreboard"];
  };
  "/api/games/{id}/participants": {
    /** Get game participants (admin) */
    get: operations["getGameParticipants"];
  };
  "/api/games/{id}/participants/{teamId}": {
    /** Update participant status in a game (admin) */
    put: operations["updateGameParticipant"];
    /** Remove participant from a game (admin) */
    delete: operations["deleteGameParticipant"];
  };
  "/api/admin/games/{id}": {
    /** Delete a game and its game-scoped relations (admin) */
    delete: operations["deleteAdminGame"];
  };
  "/api/admin/games/import": {
    /** Import a game package (admin) */
    post: operations["importAdminGamePackage"];
  };
  "/api/admin/games/{id}/export": {
    /** Export a game package (admin) */
    post: operations["exportAdminGamePackage"];
  };
  "/api/admin/games/{id}/challenges": {
    /** Get full mounted challenges for management (admin) */
    get: operations["getAdminGameChallenges"];
  };
  "/api/admin/games/{id}/instances": {
    /** List current instance leases for a game (admin) */
    get: operations["getAdminGameInstances"];
  };
  "/api/admin/games/{id}/instances/{leaseId}": {
    /** Destroy a game instance lease (admin) */
    delete: operations["deleteAdminGameInstance"];
  };
  "/api/admin/games/{id}/writeups": {
    /** List game writeups for review (admin) */
    get: operations["getAdminGameWriteups"];
  };
  "/api/admin/games/{id}/writeups/{teamId}": {
    /** Review a game writeup (admin) */
    put: operations["updateAdminGameWriteup"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: string;
    };
    MessageResponse: {
      message: string;
    };
    UserInfo: {
      id: number;
      username: string;
      email: string;
      /** @enum {string} */
      role: "user" | "team_captain" | "judge" | "admin" | "super_admin";
      /** @enum {string} */
      status: "active" | "banned";
      /** Format: date-time */
      created_at?: string;
    };
    RegisterRequest: {
      username: string;
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** @description Username or email */
      username: string;
      password: string;
    };
    AuthResponse: {
      token: string;
      user: components["schemas"]["UserInfo"];
    };
    AuthSetupStatusResponse: {
      bootstrap_admin_available: boolean;
      default_admin_username?: string;
      default_admin_password?: string;
    };
    Team: {
      id: number;
      name: string;
      invite_code: string;
      /** Format: date-time */
      created_at?: string;
      members?: components["schemas"]["TeamMember"][];
      lock?: components["schemas"]["TeamLockSummary"];
    };
    TeamLockSummary: {
      locked: boolean;
      reason?: string;
      games: components["schemas"]["TeamLockGame"][];
    };
    TeamLockGame: {
      game_id: number;
      name: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
    };
    TeamMember: {
      id: number;
      user_id: number;
      team_id: number;
      role: string;
    };
    CreateTeamRequest: {
      name: string;
    };
    JoinTeamRequest: {
      invite_code: string;
    };
    Challenge: {
      id: number;
      title: string;
      description?: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type: "static" | "dynamic";
      /** @enum {string} */
      difficulty?: "easy" | "medium" | "hard";
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      hints?: string;
      attachments?: string;
      is_visible?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    CreateChallengeRequest: {
      title: string;
      description?: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type?: "static" | "dynamic";
      /** @enum {string} */
      difficulty?: "easy" | "medium" | "hard";
      flag: string;
      flag_format?: string;
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      max_attempts?: number;
      hints?: string;
      attachments?: string;
      container_spec?: string;
      is_visible?: boolean;
    };
    UpdateChallengeRequest: {
      title?: string;
      description?: string;
      category?: string;
      type?: string;
      difficulty?: string;
      flag?: string;
      flag_format?: string;
      base_score?: number;
      min_score?: number;
      decay_rate?: number;
      max_attempts?: number;
      hints?: string;
      attachments?: string;
      container_spec?: string;
      is_visible?: boolean;
    };
    SubmitFlagRequest: {
      flag: string;
      game_id: number;
    };
    SubmitResult: {
      correct: boolean;
      is_practice?: boolean;
      score?: number;
      /** @enum {string} */
      blood_type?: "first" | "second" | "third";
      message: string;
    };
    Game: {
      id: number;
      name: string;
      description?: string;
      notice?: string;
      invitation_code?: string;
      divisions?: string[];
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** Format: date-time */
      scoreboard_freeze_at?: string | null;
      /** @enum {string} */
      status: "draft" | "active" | "ended";
      /** @enum {string} */
      registration_mode?: "review" | "auto_accept";
      max_team_members?: number;
      practice_mode?: boolean;
      writeup_required?: boolean;
      /** Format: date-time */
      writeup_deadline?: string | null;
      is_public?: boolean;
      invitation_required?: boolean;
      created_by?: number;
      /** Format: date-time */
      created_at?: string;
    };
    CreateGameRequest: {
      name: string;
      description?: string;
      notice?: string;
      invitation_code?: string;
      divisions?: string[];
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** Format: date-time */
      scoreboard_freeze_at?: string | null;
      /** @enum {string} */
      registration_mode?: "review" | "auto_accept";
      max_team_members?: number;
      practice_mode?: boolean;
      writeup_required?: boolean;
      /** Format: date-time */
      writeup_deadline?: string | null;
      is_public?: boolean;
    };
    UpdateGameRequest: {
      name?: string;
      description?: string;
      notice?: string;
      invitation_code?: string;
      divisions?: string[];
      /** Format: date-time */
      start_time?: string;
      /** Format: date-time */
      end_time?: string;
      /** Format: date-time */
      scoreboard_freeze_at?: string | null;
      /** @enum {string} */
      status?: "draft" | "active" | "ended";
      /** @enum {string} */
      registration_mode?: "review" | "auto_accept";
      max_team_members?: number;
      practice_mode?: boolean;
      writeup_required?: boolean;
      /** Format: date-time */
      writeup_deadline?: string | null;
      is_public?: boolean;
    };
    AddChallengeToGameRequest: {
      challenge_id: number;
      score_override?: number;
    };
    GameChallengeDetail: {
      id: number;
      title: string;
      description?: string;
      /** @enum {string} */
      category: "web" | "pwn" | "crypto" | "reverse" | "misc" | "forensics" | "awd";
      /** @enum {string} */
      type: "static" | "dynamic";
      difficulty?: string;
      hints?: string;
      attachments?: string;
      container_spec?: string;
      score: number;
      solved?: boolean;
      solve_count?: number;
      blood_team?: string;
      second_blood_team?: string;
      third_blood_team?: string;
    };
    ChallengeInstance: {
      game_id: number;
      challenge_id: number;
      team_id: number;
      /** @enum {string} */
      status: "idle" | "running";
      policy: components["schemas"]["ChallengeInstancePolicy"];
      provider?: string;
      image?: string;
      launch_url?: string;
      host?: string;
      port?: string;
      command?: string;
      note?: string;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      last_renewed_at?: string | null;
      /** Format: date-time */
      expires_at?: string | null;
      seconds_left: number;
      can_start: boolean;
      can_renew: boolean;
      message: string;
    };
    ChallengeInstancePolicy: {
      lease_duration_minutes: number;
      extension_duration_minutes: number;
      renewal_window_minutes: number;
      team_active_limit: number;
    };
    AdminGameInstanceLease: {
      id: number;
      game_id: number;
      team_id: number;
      team_name: string;
      challenge_id: number;
      challenge_title: string;
      status: string;
      provider?: string;
      image?: string;
      launch_url?: string;
      host?: string;
      port?: string;
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      last_renewed_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: date-time */
      stopped_at?: string | null;
      seconds_left: number;
      is_expired: boolean;
    };
    JoinGameRequest: {
      team_id: number;
      invitation_code?: string;
    };
    GameSubmitFlagRequest: {
      flag: string;
      team_id: number;
    };
    ScoreboardEntry: {
      rank: number;
      team_id: number;
      team_name: string;
      score: number;
      solve_count: number;
      /** Format: date-time */
      last_solve?: string;
    };
    ScoreboardChallengeStat: {
      id: number;
      title: string;
      category: string;
      score: number;
      solved_count: number;
      blood_team?: string;
      second_blood_team?: string;
      third_blood_team?: string;
    };
    Scoreboard: {
      game_id: number;
      division?: string;
      divisions?: string[];
      is_frozen?: boolean;
      /** Format: date-time */
      freeze_time?: string;
      entries: components["schemas"]["ScoreboardEntry"][];
      challenges?: components["schemas"]["ScoreboardChallengeStat"][];
    };
    GameParticipation: {
      has_team: boolean;
      participated: boolean;
      /** @enum {string} */
      status?: "pending" | "accepted" | "rejected";
      division?: string;
      team?: {
        id: number;
        name: string;
      };
      writeup_required?: boolean;
      writeup_submitted?: boolean;
      /** @enum {string} */
      writeup_status?: "submitted" | "approved" | "rejected";
      /** Format: date-time */
      writeup_deadline?: string | null;
      writeup_deadline_passed?: boolean;
      missing_writeup?: boolean;
      divisions?: string[];
    };
    GameParticipantEntry: {
      team_id: number;
      team_name: string;
      /** @enum {string} */
      status: "pending" | "accepted" | "rejected";
      division?: string;
      /** Format: date-time */
      joined_at: string;
      score: number;
      solve_count: number;
    };
    UpdateParticipationStatusRequest: {
      /** @enum {string} */
      status: "pending" | "accepted" | "rejected";
      division?: string | null;
    };
    ReviewGameWriteupRequest: {
      /** @enum {string} */
      status: "approved" | "rejected";
      remark?: string;
    };
    GameWriteup: {
      game_id: number;
      team_id: number;
      team_name: string;
      submitted_by: number;
      content: string;
      /** @enum {string} */
      status: "submitted" | "approved" | "rejected";
      reviewer_id?: number | null;
      review_remark: string;
      /** Format: date-time */
      submitted_at: string;
      /** Format: date-time */
      reviewed_at?: string | null;
      can_submit: boolean;
    };
    SubmitGameWriteupRequest: {
      content: string;
    };
    HealthResponse: {
      status: string;
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health check */
  healthz: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Register a new user */
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Registered and logged in */
      201: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Username or email already exists */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Login with username or email */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get auth bootstrap setup status */
  getAuthSetupStatus: {
    responses: {
      /** @description Current bootstrap auth availability */
      200: {
        content: {
          "application/json": components["schemas"]["AuthSetupStatusResponse"];
        };
      };
      /** @description Failed to inspect auth setup status */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Invalidate session */
  logout: {
    responses: {
      /** @description Logged out */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Get current user info */
  getMe: {
    responses: {
      /** @description Current user */
      200: {
        content: {
          "application/json": {
            user: components["schemas"]["UserInfo"];
          };
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create a team */
  createTeam: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamRequest"];
      };
    };
    responses: {
      /** @description Team created */
      201: {
        content: {
          "application/json": {
            team: components["schemas"]["Team"];
          };
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get my team */
  getMyTeam: {
    responses: {
      /** @description My team */
      200: {
        content: {
          "application/json": {
            team: components["schemas"]["Team"];
          };
        };
      };
      /** @description Not in any team */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Join a team by invite code */
  joinTeam: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinTeamRequest"];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Already in a team */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Leave current team */
  leaveTeam: {
    responses: {
      /** @description Left */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Cannot leave */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Remove a team member (captain only) */
  removeTeamMember: {
    parameters: {
      path: {
        teamId: number;
        memberId: number;
      };
    };
    responses: {
      /** @description Removed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Cannot remove */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List challenges */
  listChallenges: {
    parameters: {
      query?: {
        category?: string;
        show_hidden?: boolean;
      };
    };
    responses: {
      /** @description Challenge list */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"][];
        };
      };
    };
  };
  /** Create a challenge (admin) */
  createChallenge: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateChallengeRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
    };
  };
  /** Get a challenge */
  getChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Challenge */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update a challenge (admin) */
  updateChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateChallengeRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
    };
  };
  /** Delete a challenge (admin) */
  deleteChallenge: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Submit flag for standalone challenge */
  submitChallengeFlag: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitFlagRequest"];
      };
    };
    responses: {
      /** @description Correct flag */
      200: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
      /** @description Wrong flag */
      403: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
    };
  };
  /** List games */
  listGames: {
    parameters: {
      query?: {
        all?: boolean;
      };
    };
    responses: {
      /** @description Game list */
      200: {
        content: {
          "application/json": components["schemas"]["Game"][];
        };
      };
    };
  };
  /** Create a game (admin) */
  createGame: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
    };
  };
  /** Get a game */
  getGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Game */
      200: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update a game (admin) */
  updateGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGameRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
    };
  };
  /** Join a game with a team */
  joinGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinGameRequest"];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Already joined */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get my participation status in a game */
  getGameParticipation: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Participation status */
      200: {
        content: {
          "application/json": components["schemas"]["GameParticipation"];
        };
      };
      /** @description Game not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get my game writeup */
  getGameWriteup: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Writeup */
      200: {
        content: {
          "application/json": components["schemas"]["GameWriteup"];
        };
      };
      /** @description Game not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Submit or update my game writeup */
  submitGameWriteup: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitGameWriteupRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["GameWriteup"];
        };
      };
    };
  };
  /** Leave a game */
  leaveGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinGameRequest"];
      };
    };
    responses: {
      /** @description Left */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Get challenges in a game */
  getGameChallenges: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Challenge list */
      200: {
        content: {
          "application/json": components["schemas"]["GameChallengeDetail"][];
        };
      };
    };
  };
  /** Add a challenge to a game (admin) */
  addChallengeToGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddChallengeToGameRequest"];
      };
    };
    responses: {
      /** @description Added */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Remove a challenge from a game (admin) */
  removeChallengeFromGame: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    responses: {
      /** @description Removed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Submit flag for a challenge in a game */
  submitGameFlag: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GameSubmitFlagRequest"];
      };
    };
    responses: {
      /** @description Correct */
      200: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
      /** @description Wrong flag */
      403: {
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
    };
  };
  /** Get current team challenge instance lease */
  getChallengeInstance: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    responses: {
      /** @description Current challenge instance lease */
      200: {
        content: {
          "application/json": components["schemas"]["ChallengeInstance"];
        };
      };
      /** @description Instance lease unavailable in current state */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Game or challenge not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Start or renew current team challenge instance lease */
  ensureChallengeInstance: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    responses: {
      /** @description Lease started or renewed */
      200: {
        content: {
          "application/json": components["schemas"]["ChallengeInstance"];
        };
      };
      /** @description Instance lease unavailable in current state */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Game or challenge not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Destroy current team challenge instance lease */
  destroyChallengeInstance: {
    parameters: {
      path: {
        id: number;
        challengeId: number;
      };
    };
    responses: {
      /** @description Lease destroyed or already idle */
      200: {
        content: {
          "application/json": components["schemas"]["ChallengeInstance"];
        };
      };
      /** @description Instance lease unavailable in current state */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Game or challenge not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get game scoreboard */
  getScoreboard: {
    parameters: {
      query?: {
        division?: string;
      };
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Scoreboard */
      200: {
        content: {
          "application/json": components["schemas"]["Scoreboard"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get game participants (admin) */
  getGameParticipants: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Participants */
      200: {
        content: {
          "application/json": components["schemas"]["GameParticipantEntry"][];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Update participant status in a game (admin) */
  updateGameParticipant: {
    parameters: {
      path: {
        id: number;
        teamId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateParticipationStatusRequest"];
      };
    };
    responses: {
      /** @description Updated participant */
      200: {
        content: {
          "application/json": components["schemas"]["GameParticipantEntry"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Remove participant from a game (admin) */
  deleteGameParticipant: {
    parameters: {
      path: {
        id: number;
        teamId: number;
      };
    };
    responses: {
      /** @description Removed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Delete a game and its game-scoped relations (admin) */
  deleteAdminGame: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Import a game package (admin) */
  importAdminGamePackage: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Imported */
      201: {
        content: {
          "application/json": components["schemas"]["Game"];
        };
      };
    };
  };
  /** Export a game package (admin) */
  exportAdminGamePackage: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description ZIP package download */
      200: {
        content: {
          "application/zip": string;
        };
      };
    };
  };
  /** Get full mounted challenges for management (admin) */
  getAdminGameChallenges: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Mounted challenge list */
      200: {
        content: {
          "application/json": components["schemas"]["GameChallengeDetail"][];
        };
      };
    };
  };
  /** List current instance leases for a game (admin) */
  getAdminGameInstances: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Instance lease list */
      200: {
        content: {
          "application/json": components["schemas"]["AdminGameInstanceLease"][];
        };
      };
    };
  };
  /** Destroy a game instance lease (admin) */
  deleteAdminGameInstance: {
    parameters: {
      path: {
        id: number;
        leaseId: number;
      };
    };
    responses: {
      /** @description Lease destroyed */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** List game writeups for review (admin) */
  getAdminGameWriteups: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Writeup list */
      200: {
        content: {
          "application/json": components["schemas"]["GameWriteup"][];
        };
      };
    };
  };
  /** Review a game writeup (admin) */
  updateAdminGameWriteup: {
    parameters: {
      path: {
        id: number;
        teamId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewGameWriteupRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": components["schemas"]["GameWriteup"];
        };
      };
      /** @description Not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
