/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health/live": {
    get: operations["getControlPlaneLiveness"];
  };
  "/api/health/ready": {
    get: operations["getControlPlaneReadiness"];
  };
  "/api/auth/password/change": {
    post: operations["changePassword"];
  };
  "/api/auth/password/reset/request": {
    post: operations["requestPasswordReset"];
  };
  "/api/auth/password/reset/confirm": {
    post: operations["confirmPasswordReset"];
  };
  "/api/auth/email/verification/request": {
    post: operations["requestEmailVerification"];
  };
  "/api/auth/email/verification/confirm": {
    post: operations["confirmEmailVerification"];
  };
  "/api/auth/csrf": {
    get: operations["getCsrfToken"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        request_id: string;
        /** @default {} */
        fields: {
          [key: string]: string[];
        };
      };
    };
    PageInfo: {
      next_cursor: string | null;
      has_more: boolean;
    };
    PaginationRequest: {
      cursor?: string;
      /** @default 20 */
      limit: number;
    };
    ResourceVersion: number;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getControlPlaneLiveness: {
    responses: {
      /** @description Nitro process is alive */
      200: {
        content: {
          "application/json": {
            /** @constant */
            status: "ok";
            /** @constant */
            component: "control-plane";
          };
        };
      };
    };
  };
  getControlPlaneReadiness: {
    responses: {
      /** @description Control plane has required deployment configuration */
      200: {
        content: {
          "application/json": {
            /** @constant */
            status: "ready";
            /** @constant */
            component: "control-plane";
          };
        };
      };
      /** @description Control plane is not ready */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          current_password: string;
          new_password: string;
        };
      };
    };
    responses: {
      /** @description Password changed and current session refreshed */
      200: {
        content: {
          "application/json": {
            /** @constant */
            changed: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          turnstile_token?: string;
        };
      };
    };
    responses: {
      /** @description Reset request accepted without account disclosure */
      202: {
        content: {
          "application/json": {
            /** @constant */
            accepted: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
          new_password: string;
        };
      };
    };
    responses: {
      /** @description Password reset and any browser session cleared */
      200: {
        content: {
          "application/json": {
            /** @constant */
            changed: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  requestEmailVerification: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    responses: {
      /** @description Verification request accepted */
      202: {
        content: {
          "application/json": {
            /** @constant */
            accepted: true;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmEmailVerification: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
        };
      };
    };
    responses: {
      /** @description Email verified */
      200: {
        content: {
          "application/json": {
            /** @constant */
            verified: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCsrfToken: {
    responses: {
      /** @description Double-submit CSRF token and matching cookie */
      200: {
        content: {
          "application/json": {
            csrf_token: string;
          };
        };
      };
    };
  };
}
