/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health/live": {
    get: operations["getControlPlaneLiveness"];
  };
  "/api/health/ready": {
    get: operations["getControlPlaneReadiness"];
  };
  "/api/auth/register": {
    post: operations["registerIdentity"];
  };
  "/api/auth/login": {
    post: operations["loginIdentity"];
  };
  "/api/auth/me": {
    get: operations["getCurrentIdentity"];
  };
  "/api/auth/logout": {
    post: operations["logoutIdentity"];
  };
  "/api/auth/password/change": {
    post: operations["changePassword"];
  };
  "/api/auth/password/reset/request": {
    post: operations["requestPasswordReset"];
  };
  "/api/auth/password/reset/confirm": {
    post: operations["confirmPasswordReset"];
  };
  "/api/auth/email/verification/request": {
    post: operations["requestEmailVerification"];
  };
  "/api/auth/email/change": {
    post: operations["changeEmail"];
  };
  "/api/auth/email/verification/confirm": {
    post: operations["confirmEmailVerification"];
  };
  "/api/auth/csrf": {
    get: operations["getCsrfToken"];
  };
  "/api/admin/users/{userId}/role": {
    patch: operations["changeUserGlobalRole"];
  };
  "/api/admin/users": {
    get: operations["listManagedIdentities"];
  };
  "/api/admin/users/{userId}/status": {
    patch: operations["changeUserStatus"];
  };
  "/api/teams": {
    get: operations["getCurrentTeam"];
    post: operations["createTeam"];
  };
  "/api/teams/join": {
    post: operations["joinTeam"];
  };
  "/api/teams/leave": {
    post: operations["leaveTeam"];
  };
  "/api/teams/invite/rotate": {
    post: operations["rotateTeamInvite"];
  };
  "/api/teams/captain/transfer": {
    post: operations["transferTeamCaptain"];
  };
  "/api/teams/members/{userId}": {
    delete: operations["removeTeamMember"];
  };
  "/api/admin/teams/{teamId}/corrections": {
    post: operations["correctTeamMembership"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        request_id: string;
        /** @default {} */
        fields: {
          [key: string]: string[];
        };
      };
    };
    PageInfo: {
      next_cursor: string | null;
      has_more: boolean;
    };
    PaginationRequest: {
      cursor?: string;
      /** @default 20 */
      limit: number;
    };
    ResourceVersion: number;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getControlPlaneLiveness: {
    responses: {
      /** @description Nitro process is alive */
      200: {
        content: {
          "application/json": {
            /** @constant */
            status: "ok";
            /** @constant */
            component: "control-plane";
          };
        };
      };
    };
  };
  getControlPlaneReadiness: {
    responses: {
      /** @description Control plane has required deployment configuration */
      200: {
        content: {
          "application/json": {
            /** @constant */
            status: "ready";
            /** @constant */
            component: "control-plane";
          };
        };
      };
      /** @description Control plane is not ready */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  registerIdentity: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          username: string;
          /** Format: email */
          email: string;
          password: string;
          turnstile_token?: string;
        };
      };
    };
    responses: {
      /** @description Identity registered and browser session created */
      201: {
        content: {
          "application/json": {
            user: {
              id: string;
              username: string;
              /** Format: email */
              email: string;
              email_verified: boolean;
              /** @enum {string} */
              status: "active" | "banned";
              /** @enum {string} */
              role: "user" | "organizer" | "admin";
              session_version: number;
              must_change_password: boolean;
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  loginIdentity: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          identifier: string;
          password: string;
          turnstile_token?: string;
        };
      };
    };
    responses: {
      /** @description Credentials accepted and browser session created */
      200: {
        content: {
          "application/json": {
            user: {
              id: string;
              username: string;
              /** Format: email */
              email: string;
              email_verified: boolean;
              /** @enum {string} */
              status: "active" | "banned";
              /** @enum {string} */
              role: "user" | "organizer" | "admin";
              session_version: number;
              must_change_password: boolean;
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCurrentIdentity: {
    responses: {
      /** @description Current authoritative identity projection */
      200: {
        content: {
          "application/json": {
            user: {
              id: string;
              username: string;
              /** Format: email */
              email: string;
              email_verified: boolean;
              /** @enum {string} */
              status: "active" | "banned";
              /** @enum {string} */
              role: "user" | "organizer" | "admin";
              session_version: number;
              must_change_password: boolean;
            };
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logoutIdentity: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    responses: {
      /** @description Browser session cleared */
      200: {
        content: {
          "application/json": {
            /** @constant */
            logged_out: true;
          };
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          current_password: string;
          new_password: string;
        };
      };
    };
    responses: {
      /** @description Password changed and current session refreshed */
      200: {
        content: {
          "application/json": {
            /** @constant */
            changed: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          turnstile_token?: string;
        };
      };
    };
    responses: {
      /** @description Reset request accepted without account disclosure */
      202: {
        content: {
          "application/json": {
            /** @constant */
            accepted: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
          new_password: string;
        };
      };
    };
    responses: {
      /** @description Password reset and any browser session cleared */
      200: {
        content: {
          "application/json": {
            /** @constant */
            changed: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  requestEmailVerification: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    responses: {
      /** @description Verification request accepted */
      202: {
        content: {
          "application/json": {
            /** @constant */
            accepted: true;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  changeEmail: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Email changed, verification reset, and current session refreshed */
      200: {
        content: {
          "application/json": {
            /** @constant */
            changed: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmEmailVerification: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
        };
      };
    };
    responses: {
      /** @description Email verified */
      200: {
        content: {
          "application/json": {
            /** @constant */
            verified: true;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      429: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCsrfToken: {
    responses: {
      /** @description Double-submit CSRF token and matching cookie */
      200: {
        content: {
          "application/json": {
            csrf_token: string;
          };
        };
      };
    };
  };
  changeUserGlobalRole: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          role: "user" | "organizer" | "admin";
        };
      };
    };
    responses: {
      /** @description Global role changed and target sessions invalidated */
      200: {
        content: {
          "application/json": {
            user_id: string;
            /** @enum {string} */
            previous_role: "user" | "organizer" | "admin";
            /** @enum {string} */
            role: "user" | "organizer" | "admin";
            session_version: number;
            changed: boolean;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listManagedIdentities: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Cursor-paginated user management projection */
      200: {
        content: {
          "application/json": {
            items: ({
                id: string;
                username: string;
                /** Format: email */
                email: string;
                email_verified: boolean;
                /** @enum {string} */
                status: "active" | "banned";
                /** @enum {string} */
                role: "user" | "organizer" | "admin";
                session_version: number;
                must_change_password: boolean;
                /** Format: date-time */
                created_at: string;
              })[];
            page: {
              next_cursor: string | null;
              has_more: boolean;
            };
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  changeUserStatus: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          status: "active" | "banned";
        };
      };
    };
    responses: {
      /** @description User status changed and target sessions invalidated */
      200: {
        content: {
          "application/json": {
            user_id: string;
            /** @enum {string} */
            previous_status: "active" | "banned";
            /** @enum {string} */
            status: "active" | "banned";
            session_version: number;
            changed: boolean;
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCurrentTeam: {
    responses: {
      /** @description Current team or null */
      200: {
        content: {
          "application/json": {
            team: ({
              id: string;
              name: string;
              version: number;
              members: ({
                  user_id: string;
                  username: string;
                  /** @enum {string} */
                  role: "member" | "captain";
                  /** Format: date-time */
                  joined_at: string;
                })[];
              invite_code: string | null;
              lock: {
                locked: boolean;
                contests: {
                    id: string;
                    title: string;
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                  }[];
              };
            }) | null;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createTeam: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
        };
      };
    };
    responses: {
      /** @description Team created */
      201: {
        content: {
          "application/json": {
            team: {
              id: string;
              name: string;
              version: number;
              members: ({
                  user_id: string;
                  username: string;
                  /** @enum {string} */
                  role: "member" | "captain";
                  /** Format: date-time */
                  joined_at: string;
                })[];
              invite_code: string | null;
              lock: {
                locked: boolean;
                contests: {
                    id: string;
                    title: string;
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                  }[];
              };
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  joinTeam: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          invite_code: string;
        };
      };
    };
    responses: {
      /** @description Joined team */
      200: {
        content: {
          "application/json": {
            team: {
              id: string;
              name: string;
              version: number;
              members: ({
                  user_id: string;
                  username: string;
                  /** @enum {string} */
                  role: "member" | "captain";
                  /** Format: date-time */
                  joined_at: string;
                })[];
              invite_code: string | null;
              lock: {
                locked: boolean;
                contests: {
                    id: string;
                    title: string;
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                  }[];
              };
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  leaveTeam: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    responses: {
      /** @description Left team */
      200: {
        content: {
          "application/json": {
            /** @constant */
            left: true;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  rotateTeamInvite: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    responses: {
      /** @description Invite rotated */
      200: {
        content: {
          "application/json": {
            invite_code: string;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  transferTeamCaptain: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          user_id: string;
        };
      };
    };
    responses: {
      /** @description Captain transferred */
      200: {
        content: {
          "application/json": {
            team: {
              id: string;
              name: string;
              version: number;
              members: ({
                  user_id: string;
                  username: string;
                  /** @enum {string} */
                  role: "member" | "captain";
                  /** Format: date-time */
                  joined_at: string;
                })[];
              invite_code: string | null;
              lock: {
                locked: boolean;
                contests: {
                    id: string;
                    title: string;
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                  }[];
              };
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  removeTeamMember: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description Member removed */
      200: {
        content: {
          "application/json": {
            /** @constant */
            removed: true;
          };
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  correctTeamMembership: {
    parameters: {
      header: {
        /** @description Must match the configured public control-plane origin. */
        Origin: string;
        /** @description Double-submit proof matching the sauryctf-csrf cookie. */
        "X-CSRF-Token": string;
      };
      path: {
        teamId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          operation: "add_member" | "remove_member" | "transfer_captain";
          user_id: string;
          reason: string;
          /** @constant */
          confirm: true;
        };
      };
    };
    responses: {
      /** @description Team membership corrected with audit evidence */
      200: {
        content: {
          "application/json": {
            team: {
              id: string;
              name: string;
              version: number;
              members: ({
                  user_id: string;
                  username: string;
                  /** @enum {string} */
                  role: "member" | "captain";
                  /** Format: date-time */
                  joined_at: string;
                })[];
              invite_code: string | null;
              lock: {
                locked: boolean;
                contests: {
                    id: string;
                    title: string;
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                  }[];
              };
            };
          };
        };
      };
      /** @description Stable API error */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stable API error */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
